const KEY='casaAllegraPWA_v2';
const SYNC_KEY='casaAllegraSync_v1';
const DEFAULT={settings:{business:'CASA ALLEGRA',phone:'',address:'',social:'',overhead:10},products:[],quotes:[],orders:[],ideas:[],updatedAt:0};
let data=loadData(), quoteLines=[], syncClient=null, syncTimer=null, syncBusy=false, suspendSync=false;
function loadData(){try{return {...DEFAULT,...JSON.parse(localStorage.getItem(KEY)||'{}'),settings:{...DEFAULT.settings,...(JSON.parse(localStorage.getItem(KEY)||'{}').settings||{})}}}catch{return structuredClone(DEFAULT)}}
function save(localOnly=false){data.updatedAt=Date.now();localStorage.setItem(KEY,JSON.stringify(data));renderAll();if(!localOnly && !suspendSync) queueSync()}
function uid(p){return p+'_'+Date.now().toString(36)+Math.random().toString(36).slice(2,7)}
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function money(v){return new Intl.NumberFormat('es-AR',{style:'currency',currency:'ARS',maximumFractionDigits:0}).format(Number(v)||0)}
function dateStr(v){return new Date(v).toLocaleDateString('es-AR')}
function cost(p){return (+p.supplies||0)+(+p.labor||0)+(+p.other||0)}
function overhead(p){return cost(p)*(+data.settings.overhead||0)/100}
function baseCost(p){return cost(p)+overhead(p)}
function suggested(p){const base=baseCost(p),m=Math.min(.95,Math.max(0,(+p.margin||0)/100));return base?base/(1-m):0}
function margin(p){const c=baseCost(p),pr=+p.price||suggested(p);return pr?((pr-c)/pr)*100:0}
function statusClass(s){return String(s).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\s+/g,'-')}
function toast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove('show'),2200)}
function go(id){document.querySelectorAll('.section').forEach(x=>x.classList.toggle('active',x.id===id));document.querySelectorAll('.nav button,.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.section===id));const meta={inicio:['Inicio','Tu centro de gestión para crear, cotizar y organizar.'],catalogo:['Catálogo','Productos y servicios listos para mostrar y cotizar.'],costos:['Costos y precios','Calculá costo real, precio sugerido y margen por producto.'],presupuestos:['Presupuestos','Cotizaciones formales, detalladas y listas para WhatsApp.'],pedidos:['Pedidos','Seguí cada pedido desde la confirmación hasta la entrega.'],ideas:['Ideas','Guardá nuevos productos, campañas, procesos y contenidos.'],configuracion:['Configuración','Una puesta a punto simple para empezar a trabajar.']}[id];document.getElementById('pageTitle').textContent=meta[0];document.getElementById('pageSubtitle').textContent=meta[1];document.getElementById('sidebar').classList.remove('open');window.scrollTo({top:0,behavior:'smooth'})}
document.querySelectorAll('.nav button,.bottom-nav button').forEach(b=>b.addEventListener('click',()=>go(b.dataset.section)));
document.getElementById('menuBtn').addEventListener('click',()=>document.getElementById('sidebar').classList.toggle('open'));
function openModal(id){document.getElementById(id).classList.add('show')}function closeModal(id){document.getElementById(id).classList.remove('show')}
function openQuickHelp(){openModal('helpModal')}
function fillSettings(){sBusiness.value=data.settings.business;sPhone.value=data.settings.phone;sAddress.value=data.settings.address;sSocial.value=data.settings.social;sOverhead.value=data.settings.overhead}
function saveSettings(){data.settings={...data.settings,business:sBusiness.value.trim()||'CASA ALLEGRA',phone:sPhone.value.replace(/\D/g,''),address:sAddress.value.trim(),social:sSocial.value.trim(),overhead:Math.max(0,Math.min(300,+sOverhead.value||0))};save();toast('Configuración guardada')}
function openProductModal(id=''){productForm.reset();productId.value='';productModalTitle.textContent=id?'Editar producto':'Nuevo producto';pMargin.value=40;if(id){const p=data.products.find(x=>x.id===id);if(!p)return;Object.assign(window,{productId, pName,pCategory,pDesc,pImage,pSku,pSupplies,pLabor,pOther,pMargin,pPrice,pStock,pTags});productId.value=p.id;pName.value=p.name;pCategory.value=p.category;pDesc.value=p.desc||'';pImage.value=p.image||'';pSku.value=p.sku||'';pSupplies.value=p.supplies||0;pLabor.value=p.labor||0;pOther.value=p.other||0;pMargin.value=p.margin||0;pPrice.value=p.price||0;pStock.value=p.stock||0;pTags.value=(p.tags||[]).join(', ')}updatePreview();openModal('productModal')}
['pSupplies','pLabor','pOther','pMargin','pPrice'].forEach(id=>document.getElementById(id).addEventListener('input',updatePreview));
function updatePreview(){const p={supplies:+pSupplies.value||0,labor:+pLabor.value||0,other:+pOther.value||0,margin:+pMargin.value||0,price:+pPrice.value||0};previewCost.textContent=money(cost(p));previewPrice.textContent=money(suggested(p));previewMargin.textContent=margin(p).toFixed(1)+'%'}
function saveProduct(e){e.preventDefault();const id=productId.value||uid('prd');const p={id,name:pName.value.trim(),category:pCategory.value.trim()||'Sin categoría',desc:pDesc.value.trim(),image:pImage.value.trim(),sku:pSku.value.trim(),supplies:+pSupplies.value||0,labor:+pLabor.value||0,other:+pOther.value||0,margin:+pMargin.value||0,price:+pPrice.value||0,stock:+pStock.value||0,tags:pTags.value.split(',').map(x=>x.trim()).filter(Boolean),updatedAt:new Date().toISOString()};if(!p.price)p.price=Math.round(suggested(p));const i=data.products.findIndex(x=>x.id===id);if(i>=0)data.products[i]=p;else data.products.unshift(p);save();closeModal('productModal');go('catalogo');toast('Producto guardado')}
function deleteProduct(id){if(confirm('¿Eliminar este producto?')){data.products=data.products.filter(x=>x.id!==id);save();toast('Producto eliminado')}}

function getSyncConfig(){try{return JSON.parse(localStorage.getItem(SYNC_KEY)||'{}')}catch{return {}}}
function setSyncStatus(text,kind=''){const el=document.getElementById('syncStatus');if(!el)return;el.textContent=text;el.className='sync-status '+(kind?('sync-'+kind):'')}
function fillSyncConfig(){const c=getSyncConfig();if(document.getElementById('syncUrl'))syncUrl.value=c.url||'';if(document.getElementById('syncKey'))syncKey.value=c.key||'';if(document.getElementById('syncEmail'))syncEmail.value=c.email||'';setSyncStatus(c.url&&c.key?'Conexión configurada.':'Sin configurar.')}
function getSupabaseClient(){const c=getSyncConfig();if(!c.url||!c.key||!window.supabase)return null;if(!syncClient)syncClient=window.supabase.createClient(c.url,c.key,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});return syncClient}
function saveSyncConfig(){const url=document.getElementById('syncUrl').value.trim().replace(/\/$/,'');const key=document.getElementById('syncKey').value.trim();const email=document.getElementById('syncEmail').value.trim();localStorage.setItem(SYNC_KEY,JSON.stringify({url,key,email}));syncClient=null;setSyncStatus(url&&key?'Conexión guardada. Ahora iniciá sesión.':'Faltan URL y clave pública.','error');toast(url&&key?'Conexión guardada':'Completá URL y clave')}
async function registerSyncAccount(){try{saveSyncConfig();const c=getSyncConfig();const client=getSupabaseClient();if(!client)throw new Error('Falta configurar Supabase');const email=c.email,password=document.getElementById('syncPassword').value;if(!email||!password)throw new Error('Completá correo y contraseña');const r=await client.auth.signUp({email,password});if(r.error)throw r.error;setSyncStatus(r.data.session?'Cuenta creada y sesión iniciada.':'Cuenta creada. Revisá tu correo para confirmar la cuenta.','ok');toast(r.data.session?'Cuenta creada':'Revisá tu correo')}catch(e){setSyncStatus('No se pudo crear la cuenta: '+e.message,'error');toast('Error de cuenta')}}
async function loginSyncAccount(){try{saveSyncConfig();const c=getSyncConfig();const client=getSupabaseClient();if(!client)throw new Error('Falta configurar Supabase');const password=document.getElementById('syncPassword').value;const {data:r,error}=await client.auth.signInWithPassword({email:c.email,password});if(error)throw error;setSyncStatus('Conectado como '+(r.user?.email||'usuario')+'.','ok');toast('Nube conectada');await syncNow('smart');startSyncHeartbeat()}catch(e){setSyncStatus('No se pudo iniciar sesión: '+e.message,'error');toast('No se pudo iniciar sesión')}}
async function logoutSyncAccount(){const client=getSupabaseClient();if(client)await client.auth.signOut();setSyncStatus('Sesión de nube cerrada.');toast('Sesión cerrada')}
async function syncNow(mode='smart'){if(syncBusy)return;const client=getSupabaseClient();if(!client){setSyncStatus('Configurá primero la conexión a Supabase.','error');return}syncBusy=true;try{const {data:{user},error:ue}=await client.auth.getUser();if(ue||!user)throw new Error('Iniciá sesión en la nube');const {data:remote,error}=await client.from('business_state').select('id,user_id,payload,updated_at').eq('user_id',user.id).maybeSingle();if(error)throw error;const localStamp=Number(data.updatedAt||0);const remoteStamp=Number(remote?.payload?.updatedAt||0);
if(mode==='upload' || (!remote && localStamp>0) || (mode==='smart' && localStamp>=remoteStamp)){const payload=JSON.parse(JSON.stringify(data));const {error:e}=await client.from('business_state').upsert({user_id:user.id,payload,updated_at:new Date().toISOString()},{onConflict:'user_id'});if(e)throw e;setSyncStatus('Sincronizado desde este dispositivo · '+new Date().toLocaleTimeString('es-AR'),'ok');}
else if(remote){suspendSync=true;data={...DEFAULT,...remote.payload,settings:{...DEFAULT.settings,...(remote.payload.settings||{})}};localStorage.setItem(KEY,JSON.stringify(data));renderAll();suspendSync=false;setSyncStatus('Datos traídos de la nube · '+new Date().toLocaleTimeString('es-AR'),'ok');}
else setSyncStatus('No hay datos en la nube todavía.','ok');
}catch(e){suspendSync=false;setSyncStatus('Sincronización: '+e.message,'error')}finally{syncBusy=false}}
function queueSync(){clearTimeout(syncTimer);syncTimer=setTimeout(()=>syncNow('smart'),1800)}
function startSyncHeartbeat(){clearInterval(window.casaSyncInterval);window.casaSyncInterval=setInterval(()=>syncNow('smart'),15000)}
async function initSync(){fillSyncConfig();if(document.getElementById('autoStartToggle')&&window.casaAllegraDesktop){try{document.getElementById('autoStartToggle').checked=await window.casaAllegraDesktop.getAutoStart()}catch{}}const client=getSupabaseClient();if(client){client.auth.onAuthStateChange((_event,session)=>{if(session){setSyncStatus('Conectado como '+(session.user?.email||'usuario')+'.','ok');syncNow('smart');startSyncHeartbeat()}else setSyncStatus('Conexión configurada. Iniciá sesión.')});const {data:{session}}=await client.auth.getSession();if(session){setSyncStatus('Conectado como '+(session.user?.email||'usuario')+'.','ok');syncNow('smart');startSyncHeartbeat()}}}
async function toggleAutoStart(enabled){if(window.casaAllegraDesktop){const result=await window.casaAllegraDesktop.setAutoStart(enabled);toast(result?'Se abrirá con Windows':'Autoinicio desactivado')}else toast('Esta opción funciona en Windows de escritorio')}

function renderCatalog(){const s=(productSearch.value||'').toLowerCase(),cat=productCategory.value,view=productView.value,items=data.products.filter(p=>(!cat||p.category===cat)&&(p.name+' '+p.desc+' '+(p.tags||[]).join(' ')).toLowerCase().includes(s));products.className='product-grid '+view;products.innerHTML=items.length?items.map(p=>`<article class="card product"><div class="product-image">${p.image?`<img src="${esc(p.image)}" alt="${esc(p.name)}" onerror="this.outerHTML='<span>✦</span>'">`:'✦'}</div><div class="product-body"><div class="product-top"><span class="badge">${esc(p.category)}</span><span class="meta">${esc(p.sku||'')}</span></div><h3>${esc(p.name)}</h3><p>${esc(p.desc||'Sin descripción')}</p><div class="flex" style="justify-content:space-between;margin-top:10px"><span class="price">${money(p.price)}</span><span class="meta">Stock: ${p.stock}</span></div><div class="product-actions"><button class="btn" onclick="openProductModal('${p.id}')">Editar</button><button class="btn" onclick="shareProduct('${p.id}')">WhatsApp</button><button class="btn danger-outline" onclick="deleteProduct('${p.id}')">Eliminar</button></div></div></article>`).join(''):'<div class="card panel">No hay productos todavía. Empezá con <button class="btn primary" onclick="openProductModal()">+ Producto</button>.</div>';const cats=[...new Set(data.products.map(p=>p.category).filter(Boolean))].sort();const old=productCategory.value;productCategory.innerHTML='<option value="">Todas las categorías</option>'+cats.map(c=>`<option value="${esc(c)}" ${c===old?'selected':''}>${esc(c)}</option>`).join('')}
function renderPricing(){const s=(document.getElementById('costos').classList.contains('active')?1:0);const q=(document.getElementById('priceSearch')?.value||'').toLowerCase();const items=data.products.filter(p=>p.name.toLowerCase().includes(q));pricing.innerHTML=items.length?items.map(p=>{const c=cost(p),op=overhead(p),base=baseCost(p),sp=suggested(p),m=margin(p);return `<div class="card price-card"><div class="flex" style="justify-content:space-between"><div><h3 style="margin:0">${esc(p.name)}</h3><span class="meta">${esc(p.category)}</span></div><button class="btn" onclick="openProductModal('${p.id}')">Editar</button></div><div class="price-grid"><div class="metric"><span>Costo directo</span><strong>${money(c)}</strong><small class="meta">Insumos + mano de obra + otros</small></div><div class="metric"><span>Gastos operativos</span><strong>${money(op)}</strong><small class="meta">${data.settings.overhead}%</small></div><div class="metric"><span>Precio actual</span><strong>${money(p.price)}</strong></div><div class="metric"><span>Precio sugerido</span><strong>${money(sp)}</strong></div><div class="metric"><span>Margen actual</span><strong class="${m>=40?'margin-good':'margin-low'}">${m.toFixed(1)}%</strong></div></div><div class="notice" style="margin-top:12px">Costo base para precio: <b>${money(base)}</b> · margen deseado: <b>${(+p.margin||0).toFixed(1)}%</b></div></div>`}).join(''):'<div class="card panel">No hay productos para calcular. Cargá uno desde <button class="btn primary" onclick="openProductModal()">+ Nuevo producto</button>.</div>'}
function addQuoteLine(productId=''){quoteLines.push({productId:productId||data.products[0]?.id||'',qty:1});renderQuoteLines();updateQuoteTotal()}
function openQuoteModal(){quoteForm.reset();qValidity.value='7 días';qDiscount.value=0;quoteLines=[];addQuoteLine();openModal('quoteModal')}
function renderQuoteLines(){const qLinesDom=document.getElementById('quoteLines');qLinesDom.innerHTML=quoteLines.length?quoteLines.map((l,i)=>`<div class="quote-line"><select class="select" onchange="quoteLines[${i}].productId=this.value;updateQuoteTotal()">${data.products.map(p=>`<option value="${p.id}" ${p.id===l.productId?'selected':''}>${esc(p.name)} · ${money(p.price)}</option>`).join('')}</select><input class="input" type="number" min="1" value="${l.qty}" onchange="quoteLines[${i}].qty=Math.max(1,+this.value||1);updateQuoteTotal()"><strong class="line-price">${money(lineTotal(l))}</strong><button type="button" class="icon-btn" onclick="quoteLines.splice(${i},1);renderQuoteLines();updateQuoteTotal()">×</button></div>`).join(''):'<div class="notice">Agregá al menos un producto.</div>'}
function lineTotal(l){const p=data.products.find(x=>x.id===l.productId);return p?(+p.price||0)*(+l.qty||1):0}
function updateQuoteTotal(){const sub=quoteLines.reduce((a,l)=>a+lineTotal(l),0);quoteSubtotal.textContent=money(sub);quoteTotal.textContent=money(Math.max(0,sub-(+qDiscount.value||0)));renderQuoteLines()}
function saveQuote(e){e.preventDefault();const items=quoteLines.filter(l=>data.products.some(p=>p.id===l.productId));if(!items.length){toast('Agregá al menos un producto');return}const sub=items.reduce((a,l)=>a+lineTotal(l),0),discount=+qDiscount.value||0,total=Math.max(0,sub-discount);const num='CA-'+String(data.quotes.length+1).padStart(4,'0');data.quotes.unshift({id:uid('q'),number:num,client:qClient.value.trim(),phone:qPhone.value.replace(/\D/g,''),validity:qValidity.value.trim(),notes:qNotes.value.trim(),items,subtotal:sub,discount,total,status:'Pendiente',date:new Date().toISOString()});save();closeModal('quoteModal');go('presupuestos');toast('Presupuesto guardado')}
function renderQuotes(){const s=(quoteSearch.value||'').toLowerCase(),st=quoteStatus.value;const rows=data.quotes.filter(q=>(!st||q.status===st)&&(`${q.number} ${q.client} `+q.items.map(i=>data.products.find(p=>p.id===i.productId)?.name||'').join(' ')).toLowerCase().includes(s));quotesTable.innerHTML=rows.length?rows.map(q=>`<tr><td><b>${q.number}</b></td><td>${esc(q.client)}</td><td>${dateStr(q.date)}</td><td>${money(q.total)}</td><td><span class="pill-status">${esc(q.status)}</span></td><td><button class="btn" onclick="shareQuote('${q.id}')">WhatsApp</button> <button class="btn" onclick="convertQuote('${q.id}')">Pedido</button> <button class="btn danger-outline" onclick="deleteQuote('${q.id}')">Eliminar</button></td></tr>`).join(''):'<tr><td colspan="6">No hay presupuestos.</td></tr>'}
function deleteQuote(id){if(confirm('¿Eliminar presupuesto?')){data.quotes=data.quotes.filter(q=>q.id!==id);save()}}
function convertQuote(id){const q=data.quotes.find(x=>x.id===id);if(!q)return;data.orders.unshift({id:uid('ord'),number:'PED-'+String(data.orders.length+1).padStart(4,'0'),quoteId:q.id,client:q.client,phone:q.phone,items:q.items,total:q.total,status:'Pendiente',origin:q.number,date:new Date().toISOString()});q.status='Aprobado';save();go('pedidos');toast('Presupuesto convertido en pedido')}
function renderOrders(){const s=(orderSearch.value||'').toLowerCase(),st=orderStatus.value;const rows=data.orders.filter(o=>(!st||o.status===st)&&(`${o.number} ${o.client} ${o.origin}`).toLowerCase().includes(s));ordersTable.innerHTML=rows.length?rows.map(o=>`<tr><td><b>${o.number}</b></td><td>${esc(o.client)}</td><td>${dateStr(o.date)}</td><td>${money(o.total)}</td><td><select class="status-select status-${statusClass(o.status)}" onchange="setOrderStatus('${o.id}',this.value)">${['Pendiente','En proceso','Listo','Entregado','Cancelado'].map(s=>`<option ${s===o.status?'selected':''}>${s}</option>`).join('')}</select></td><td>${esc(o.origin||'')}</td><td><button class="btn" onclick="shareOrder('${o.id}')">WhatsApp</button> <button class="btn danger-outline" onclick="deleteOrder('${o.id}')">Eliminar</button></td></tr>`).join(''):'<tr><td colspan="7">No hay pedidos.</td></tr>'}
function setOrderStatus(id,status){const o=data.orders.find(x=>x.id===id);if(o){o.status=status;save();toast('Estado actualizado')}}function deleteOrder(id){if(confirm('¿Eliminar pedido?')){data.orders=data.orders.filter(o=>o.id!==id);save()}}
function openIdeaModal(){document.querySelector('#ideaModal form').reset();openModal('ideaModal')}
function saveIdea(e){e.preventDefault();data.ideas.unshift({id:uid('idea'),title:iTitle.value.trim(),type:iType.value,body:iBody.value.trim(),date:new Date().toISOString()});save();closeModal('ideaModal');go('ideas');toast('Idea guardada')}
function deleteIdea(id){if(confirm('¿Eliminar esta idea?')){data.ideas=data.ideas.filter(x=>x.id!==id);save()}}
function renderIdeas(){ideasGrid.innerHTML=data.ideas.length?data.ideas.map(i=>`<article class="card idea-card"><span class="badge">${esc(i.type)}</span><h3>${esc(i.title)}</h3><p>${esc(i.body||'')}</p><div class="flex" style="justify-content:space-between;margin-top:13px"><span class="meta">${dateStr(i.date)}</span><button class="btn danger-outline" onclick="deleteIdea('${i.id}')">Eliminar</button></div></article>`).join(''):'<div class="card panel">Aún no hay ideas guardadas.</div>'}
function wa(phone,text){return phone?`https://wa.me/${phone}?text=${encodeURIComponent(text)}`:`https://wa.me/?text=${encodeURIComponent(text)}`}
function shareProduct(id){const p=data.products.find(x=>x.id===id);if(!p)return;window.open(wa('',`${data.settings.business}\n${p.name}\n${p.desc||''}\nPrecio: ${money(p.price)}\nDisponibilidad: ${p.stock>0?'Disponible':'Consultar'}`),'_blank')}
function shareQuote(id){const q=data.quotes.find(x=>x.id===id);if(!q)return;const lines=q.items.map(i=>{const p=data.products.find(x=>x.id===i.productId);return `• ${p?.name||'Producto'} x${i.qty} — ${money((p?.price||0)*i.qty)}`}).join('\n');const text=`${data.settings.business}\nPRESUPUESTO ${q.number}\nCliente: ${q.client}\n\n${lines}\n\nTotal: ${money(q.total)}\nValidez: ${q.validity||'7 días'}${q.notes?'\n'+q.notes:''}\n\nGracias por elegir ${data.settings.business}.`;window.open(wa(q.phone,text),'_blank')}
function shareOrder(id){const o=data.orders.find(x=>x.id===id);if(!o)return;window.open(wa(o.phone,`${data.settings.business}\nPEDIDO ${o.number}\nCliente: ${o.client}\nEstado: ${o.status}\nTotal: ${money(o.total)}`),'_blank')}
function shareCatalog(){const text=`${data.settings.business}\nCATÁLOGO\n\n`+data.products.slice(0,40).map(p=>`• ${p.name} — ${money(p.price)}\n${p.desc||''}`).join('\n\n');window.open(wa('',text),'_blank')}
function calcStats(){statProducts.textContent=data.products.length;statQuotes.textContent=data.quotes.length;statOrders.textContent=data.orders.filter(o=>!['Entregado','Cancelado'].includes(o.status)).length;statSales.textContent=money(data.quotes.reduce((a,q)=>a+q.total,0));const avg=data.products.length?data.products.reduce((a,p)=>a+margin(p),0)/data.products.length:0;avgMargin.textContent=avg.toFixed(1)+'%';marginBar.style.width=Math.min(100,Math.max(0,avg))+'%';pendingOrders.textContent=data.orders.filter(o=>o.status==='Pendiente').length;statIdeas.textContent=data.ideas.length}
function renderAll(){fillSettings();renderCatalog();renderPricing();renderQuotes();renderOrders();renderIdeas();calcStats()}
function loadDemo(){if(!confirm('Se reemplazarán los datos actuales por un ejemplo. ¿Continuar?'))return;data={settings:{...data.settings,business:'CASA ALLEGRA',overhead:10},products:[{id:uid('prd'),name:'Agenda personalizada A5',category:'Agendas',desc:'Tapa rígida, interior personalizado y elástico.',supplies:4500,labor:2500,other:800,margin:45,price:0,stock:18,tags:['personalizado','regalo'],sku:'AG-A5-01',image:''},{id:uid('prd'),name:'Planner semanal',category:'Organización',desc:'Planner de escritorio con hojas desprendibles.',supplies:1800,labor:900,other:300,margin:40,price:0,stock:25,tags:['planner'],sku:'PL-01',image:''},{id:uid('prd'),name:'Kit regalo escritorio',category:'Regalos',desc:'Cuaderno + lapicera + señalador en presentación regalo.',supplies:3200,labor:1200,other:500,margin:50,price:0,stock:12,tags:['regalo','combo'],sku:'KIT-01',image:''}],quotes:[],orders:[],ideas:[{id:uid('idea'),title:'Combo vuelta a clases',type:'Campaña',body:'Armar pack de cuaderno, etiquetas, lapiceras y separadores.',date:new Date().toISOString()},{id:uid('idea'),title:'Catálogo para empresas',type:'Contenido',body:'Crear una versión con regalos corporativos personalizados.',date:new Date().toISOString()}]};data.products.forEach(p=>p.price=Math.round(suggested(p)));save();toast('Ejemplo cargado')}
function clearAllData(){if(!confirm('Esto borrará todos los productos, presupuestos, pedidos e ideas. ¿Continuar?'))return;data={...DEFAULT,settings:{...DEFAULT.settings}};save();toast('Datos borrados')}
function exportData(){const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='casa-allegra-copia.json';a.click();URL.revokeObjectURL(a.href);toast('Copia exportada')}
function importData(e){const file=e.target.files?.[0];if(!file)return;const r=new FileReader();r.onload=()=>{try{const incoming=JSON.parse(r.result);if(!incoming.products||!incoming.quotes||!incoming.orders||!incoming.ideas)throw new Error();data={...DEFAULT,...incoming,settings:{...DEFAULT.settings,...(incoming.settings||{})}};save();toast('Copia importada')}catch{alert('La copia no parece ser válida.')}};r.readAsText(file);e.target.value=''}
document.addEventListener('keydown',e=>{if(e.key==='Escape')document.querySelectorAll('.modal.show').forEach(m=>m.classList.remove('show'))});document.querySelectorAll('.modal').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)m.classList.remove('show')}));
renderAll();
