/* CASA ALLEGRA — Integraciones v2 */
(function(){
  const KEY='casaAllegraIntegrations_v2';
  const DEFAULT={mercadopago:{enabled:false,mode:'sandbox',publicKey:'',connected:false},mercadolibre:{enabled:false,connected:false},mercadoenvios:{enabled:false,connected:false},correoargentino:{enabled:false,connected:false},andreani:{enabled:false,connected:false}};
  const providers=[['mercadopago','💳','Mercado Pago','Pagos online, links y estado de cobro.','Pago'],['mercadolibre','🛒','Mercado Libre','Publicaciones, ventas y sincronización de productos.','Marketplace'],['mercadoenvios','📦','Mercado Envíos','Seguimiento y estado logístico.','Envíos'],['correoargentino','📮','Correo Argentino','Despachos y códigos de seguimiento.','Correo'],['andreani','🚚','Andreani','Despachos, seguimiento y entregas.','Logística']];
  let cfg=load();
  function load(){try{return {...DEFAULT,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return JSON.parse(JSON.stringify(DEFAULT))}}
  function esc(s){return String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]))}
  function notify(msg){if(typeof window.toast==='function')window.toast(msg);else console.log(msg)}
  function style(){if(document.getElementById('integrationStyles'))return;const s=document.createElement('style');s.id='integrationStyles';s.textContent=`.integration-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px}.integration-card{padding:18px}.integration-card.is-on{box-shadow:0 0 0 2px rgba(99,199,201,.22),var(--shadow)}.integration-head{display:grid;grid-template-columns:auto 1fr auto;gap:12px;align-items:start}.integration-icon{width:50px;height:50px;border-radius:15px;background:#f5effd;display:grid;place-items:center;font-size:26px}.integration-head h3{margin:6px 0 4px}.integration-head p{margin:0;color:var(--muted);font-size:12px;line-height:1.45}.integration-switch{position:relative;width:48px;height:28px}.integration-switch input{display:none}.integration-switch span{position:absolute;inset:0;border-radius:999px;background:#ddd3df;cursor:pointer}.integration-switch span:after{content:'';position:absolute;width:22px;height:22px;left:3px;top:3px;border-radius:50%;background:#fff;box-shadow:0 2px 6px rgba(0,0,0,.12);transition:.2s}.integration-switch input:checked+span{background:var(--turq)}.integration-switch input:checked+span:after{transform:translateX(20px)}.integration-status{margin:12px 0;font-size:11px;font-weight:800}.integration-dot{display:inline-block;width:8px;height:8px;border-radius:50%;background:#c7bdc9;margin-right:7px}.integration-card.is-on .integration-dot{background:var(--success)}.integration-fields{display:grid;grid-template-columns:1fr 1fr;gap:10px}.integration-fields label{display:grid;gap:6px;color:#675e6d;font-size:11px;font-weight:800}.integration-data{margin-top:12px;padding:10px;background:#faf6fb;border-radius:12px}.integration-data span{display:block;font-size:10px;font-weight:800}.integration-data small{font-size:11px;color:var(--muted)}.integration-flow{display:flex;gap:8px;flex-wrap:wrap;align-items:center;margin-top:14px}.integration-flow span{padding:10px 12px;background:#f8f3fa;border-radius:12px;font-size:11px;font-weight:800}@media(max-width:760px){.integration-grid{grid-template-columns:1fr}.integration-fields{grid-template-columns:1fr}}`;document.head.appendChild(s)}
  function card(p){const[id,icon,name,desc,type]=p,c=cfg[id]||DEFAULT[id];return `<article class="card integration-card ${c.enabled?'is-on':''}"><div class="integration-head"><div class="integration-icon">${icon}</div><div><span class="badge">${type}</span><h3>${name}</h3><p>${desc}</p></div><label class="integration-switch"><input data-int="${id}" type="checkbox" ${c.enabled?'checked':''}><span></span></label></div><div class="integration-status"><span class="integration-dot"></span>${c.connected?'Conectado':'Preparado para conectar'}</div>${id==='mercadopago'?`<div class="integration-fields"><label>Modo<select id="mpMode" class="select"><option value="sandbox" ${c.mode==='sandbox'?'selected':''}>Pruebas / Sandbox</option><option value="production" ${c.mode==='production'?'selected':''}>Producción</option></select></label><label>Clave pública<input id="mpPublic" class="input" value="${esc(c.publicKey)}" placeholder="Se agregará al conectar la API"></label></div>`:`<div class="integration-fields"><label>Estado de conexión<input class="input" value="${c.connected?'Conectado':'Pendiente de credenciales API'}" disabled></label><button type="button" class="btn" data-info="${id}">Ver estructura</button></div>`}<div class="integration-data"><span>Datos previstos</span><small>${id==='mercadopago'?'pago_id · referencia · monto · estado':id==='mercadolibre'?'publicación · SKU · venta · comprador':id==='mercadoenvios'?'shipment_id · tracking · estado · costo':'destinatario · tracking · estado · costo'}</small></div></article>`}
  function activate(){const section=document.getElementById('integraciones');if(!section)return;document.querySelectorAll('.section').forEach(x=>x.classList.toggle('active',x===section));document.querySelectorAll('.nav button,.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.section==='integraciones'));const t=document.getElementById('pageTitle'),s=document.getElementById('pageSubtitle');if(t)t.textContent='Integraciones';if(s)s.textContent='Pagos, marketplaces y operadores logísticos.';window.scrollTo({top:0,behavior:'smooth'})}
  function render(){style();let nav=document.querySelector('.nav');if(nav&&!nav.querySelector('[data-section="integraciones"]')){const b=document.createElement('button');b.dataset.section='integraciones';b.innerHTML='🔗 <span>Integraciones</span>';b.addEventListener('click',activate);nav.appendChild(b)}let bottom=document.querySelector('.bottom-nav');if(bottom&&!bottom.querySelector('[data-section="integraciones"]')){const b=document.createElement('button');b.dataset.section='integraciones';b.innerHTML='🔗<span>Integraciones</span>';b.addEventListener('click',activate)}let section=document.getElementById('integraciones');if(!section){const main=document.querySelector('.main');if(!main)return;section=document.createElement('section');section.id='integraciones';section.className='section';section.innerHTML=`<div class="section-head"><div><h2>Integraciones</h2><p>Conectá pagos, marketplaces y operadores logísticos cuando estés listo.</p></div><button class="btn primary" id="saveIntegrationsBtn">Guardar configuración</button></div><div class="card info-banner"><strong>Centro de conexiones</strong><span>Interfaz lista. Las APIs reales se conectarán en la segunda etapa.</span></div><div class="integration-grid">${providers.map(card).join('')}</div><div class="card panel" style="margin-top:16px"><h3>Flujo de pedido</h3><div class="integration-flow"><span>🧾 Presupuesto</span><b>→</b><span>💳 Pago</span><b>→</b><span>📦 Pedido</span><b>→</b><span>🚚 Envío</span><b>→</b><span>✅ Entrega</span></div><p class="muted">Cada pedido podrá guardar proveedor, referencia externa, estado, tracking, costo y fecha de entrega.</p></div>`;main.appendChild(section)}const saveBtn=document.getElementById('saveIntegrationsBtn');if(saveBtn&&!saveBtn.dataset.bound){saveBtn.dataset.bound='1';saveBtn.addEventListener('click',save)}section.querySelectorAll('[data-int]').forEach(e=>{if(!e.dataset.bound){e.dataset.bound='1';e.addEventListener('change',()=>e.closest('.integration-card').classList.toggle('is-on',e.checked))}});section.querySelectorAll('[data-info]').forEach(e=>{if(!e.dataset.bound){e.dataset.bound='1';e.addEventListener('click',()=>{const p=providers.find(x=>x[0]===e.dataset.info);notify((p?p[2]:'Integración')+': estructura preparada para API real.')})}});const b=document.querySelector('[data-section="integraciones"]');if(b&&!b.dataset.bound){b.dataset.bound='1';b.addEventListener('click',activate)}}
  function save(){document.querySelectorAll('[data-int]').forEach(e=>{cfg[e.dataset.int]={...(cfg[e.dataset.int]||DEFAULT[e.dataset.int]),enabled:e.checked}});cfg.mercadopago={...cfg.mercadopago,mode:document.getElementById('mpMode')?.value||cfg.mercadopago.mode,publicKey:document.getElementById('mpPublic')?.value||''};localStorage.setItem(KEY,JSON.stringify(cfg));notify('Configuración de integraciones guardada')}
  window.casaAllegraIntegrations={activate,render,save};document.addEventListener('DOMContentLoaded',render);
})();

/* CASA ALLEGRA · Inicio rápido + Reportes */
(function(){
'use strict';const DATA_KEY='casaAllegraPWA_v2';
const read=()=>{try{return JSON.parse(localStorage.getItem(DATA_KEY)||'{}')}catch{return {}}};
const money=n=>new Intl.NumberFormat('es-AR',{style:'currency',currency:'ARS',maximumFractionDigits:0}).format(Number(n)||0);
const esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const dateValue=x=>new Date(x?.createdAt||x?.date||x?.updatedAt||0).getTime();
function addStyles(){if(document.getElementById('caReportsStyles'))return;const s=document.createElement('style');s.id='caReportsStyles';s.textContent=`.ca-quick-grid{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:10px}.ca-quick{border:1px solid var(--line);border-radius:16px;background:#fff;padding:14px 9px;display:grid;gap:7px;justify-items:center;font-weight:800;color:#5f5667;transition:.2s}.ca-quick:hover{transform:translateY(-2px);box-shadow:0 8px 18px rgba(67,43,88,.08)}.ca-quick-icon{font-size:22px}.ca-quick span{font-size:11px;text-align:center}.ca-report-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px;margin-top:16px}.ca-report-kpi{padding:15px}.ca-report-kpi span{display:block;color:var(--muted);font-size:11px}.ca-report-kpi strong{display:block;font-size:22px;margin-top:5px}.ca-chart{padding:18px;margin-top:16px}.ca-chart-head{display:flex;justify-content:space-between;align-items:flex-start;gap:12px}.ca-chart-head h3{margin:0}.ca-chart-head p{margin:4px 0 0;color:var(--muted);font-size:11px}.ca-bars{height:230px;display:grid;grid-template-columns:repeat(7,1fr);gap:10px;align-items:end;margin-top:18px}.ca-bar-col{height:100%;display:grid;grid-template-rows:1fr auto;align-items:end;gap:7px}.ca-bar-track{height:100%;display:flex;align-items:end;justify-content:center}.ca-bar{width:min(42px,70%);min-height:3px;border-radius:10px 10px 4px 4px;background:linear-gradient(180deg,var(--turq),var(--violet));transition:height .25s}.ca-bar-label{text-align:center;color:var(--muted);font-size:10px}.ca-chart-value{text-align:center;font-size:9px;color:var(--muted);margin-bottom:3px;white-space:nowrap}.ca-report-columns{display:grid;grid-template-columns:1.3fr .7fr;gap:16px;margin-top:16px}.ca-report-list{padding:16px}.ca-report-list h3{margin:0 0 10px}.ca-report-list-row{display:flex;justify-content:space-between;gap:12px;padding:10px 0;border-bottom:1px solid var(--line);font-size:12px}.ca-report-list-row:last-child{border-bottom:0}.ca-low{color:#c48b36;font-weight:800}@media(max-width:900px){.ca-quick-grid{grid-template-columns:repeat(3,1fr)}.ca-report-grid{grid-template-columns:repeat(2,1fr)}.ca-report-columns{grid-template-columns:1fr}}@media(max-width:600px){.ca-quick-grid{grid-template-columns:repeat(2,1fr)}.ca-report-grid{grid-template-columns:1fr 1fr}.ca-bars{gap:5px}.ca-chart{padding:14px}}`;document.head.appendChild(s)}
function goSafe(id){if(typeof window.go==='function'&&document.getElementById(id)){window.go(id);return true}return false}
function quickActions(){const home=document.getElementById('inicio');if(!home)return;const old=home.querySelector('.quick-grid');if(!old)return;old.className='ca-quick-grid';old.innerHTML=[['➕','Nuevo producto'],['🧾','Nuevo presupuesto'],['📦','Ver pedidos'],['📚','Ver catálogo'],['🧮','Costos y precios'],['💡','Ideas'],['📊','Ver reportes'],['🔗','Integraciones'],['⚙️','Configuración'],['❓','Ayuda']].map((a,i)=>`<button class="ca-quick" type="button" data-ca-quick="${i}"><b class="ca-quick-icon">${a[0]}</b><span>${a[1]}</span></button>`).join('');const actions=[()=>typeof window.openProductModal==='function'&&window.openProductModal(),()=>typeof window.openQuoteModal==='function'&&window.openQuoteModal(),()=>goSafe('pedidos'),()=>goSafe('catalogo'),()=>goSafe('costos'),()=>goSafe('ideas'),()=>showReports(),()=>typeof window.casaAllegraIntegrations?.activate==='function'&&window.casaAllegraIntegrations.activate(),()=>goSafe('configuracion'),()=>typeof window.openQuickHelp==='function'&&window.openQuickHelp()];old.querySelectorAll('[data-ca-quick]').forEach(b=>b.addEventListener('click',()=>actions[Number(b.dataset.caQuick)]?.()))}
function ensureReportNav(){const nav=document.querySelector('.nav');if(!nav||nav.querySelector('[data-section="reportes"]'))return;const b=document.createElement('button');b.dataset.section='reportes';b.innerHTML='📊 <span>Reportes</span>';b.addEventListener('click',showReports);const integ=nav.querySelector('[data-section="integraciones"]');integ?nav.insertBefore(b,integ):nav.appendChild(b)}
function ensureReportSection(){if(document.getElementById('reportes'))return;const main=document.querySelector('.main');if(!main)return;const sec=document.createElement('section');sec.id='reportes';sec.className='section ca-report-section';sec.innerHTML=`<div class="section-head"><div><h2>Reportes</h2><p>Visualizá ventas, presupuestos, pedidos, stock y rentabilidad de CASA ALLEGRA.</p></div><button class="btn primary" type="button" id="caRefreshReports">Actualizar</button></div><div class="card info-banner"><strong>Resumen de actividad</strong><span>Los datos se calculan automáticamente con la información guardada en CASA ALLEGRA.</span></div><div id="caReportKpis" class="ca-report-grid"></div><div class="card ca-chart"><div class="ca-chart-head"><div><h3>Ventas cotizadas · últimos 7 días</h3><p>Evolución del total de presupuestos creados en cada día.</p></div><span class="badge">ARS</span></div><div id="caSalesChart" class="ca-bars"></div></div><div class="ca-report-columns"><div class="card ca-report-list"><h3>Productos y stock</h3><div id="caProductReport"></div></div><div class="card ca-report-list"><h3>Pedidos por estado</h3><div id="caOrderReport"></div></div></div>`;main.appendChild(sec);document.getElementById('caRefreshReports').addEventListener('click',renderReports)}
function dataset(){const d=read(),products=d.products||[],quotes=d.quotes||[],orders=d.orders||[];const approved=quotes.filter(x=>['Aprobado','Pagado'].includes(x.status));const total=approved.reduce((a,x)=>a+(Number(x.total)||0),0);const low=products.filter(x=>(Number(x.stock)||0)<=2);const activeOrders=orders.filter(x=>['Pendiente','En proceso','Listo'].includes(x.status)).length;return{d,products,quotes,orders,total,low,activeOrders}}
function renderReports(){const x=dataset(),k=document.getElementById('caReportKpis');if(!k)return;const avg=x.products.length?x.products.reduce((a,p)=>{const c=(Number(p.supplies)||0)+(Number(p.labor)||0)+(Number(p.other)||0),op=c*(Number(x.d.settings?.overhead)||0)/100,pr=Number(p.price)||0;return a+(pr?((pr-(c+op))/pr)*100:0)},0)/x.products.length:0;k.innerHTML=[['Ventas aprobadas',money(x.total),'acumulado'],['Presupuestos',x.quotes.length,'registrados'],['Pedidos activos',x.activeOrders,'sin entregar'],['Margen promedio',avg.toFixed(1)+'%','sobre productos']].map(a=>`<div class="card ca-report-kpi"><span>${a[0]}</span><strong>${a[1]}</strong><small class="meta">${a[2]}</small></div>`).join('');const chart=document.getElementById('caSalesChart');if(chart){const days=[];for(let i=6;i>=0;i--){const day=new Date();day.setHours(0,0,0,0);day.setDate(day.getDate()-i);const next=new Date(day);next.setDate(next.getDate()+1);const val=x.quotes.filter(q=>{const t=dateValue(q);return t>=day.getTime()&&t<next.getTime()}).reduce((a,q)=>a+(Number(q.total)||0),0);days.push({label:day.toLocaleDateString('es-AR',{weekday:'short'}).replace('.',''),value:val})}const max=Math.max(...days.map(v=>v.value),1);chart.innerHTML=days.map(v=>`<div class="ca-bar-col"><div class="ca-bar-track"><div><div class="ca-chart-value">${v.value?money(v.value):'$ 0'}</div><div class="ca-bar" style="height:${Math.max(3,(v.value/max)*185)}px"></div></div></div><div class="ca-bar-label">${esc(v.label)}</div></div>`).join('')}const pr=document.getElementById('caProductReport');if(pr)pr.innerHTML=x.low.length?x.low.slice(0,8).map(p=>`<div class="ca-report-list-row"><span>${esc(p.name)}</span><b class="ca-low">Stock: ${Number(p.stock)||0}</b></div>`).join(''):'<div class="ca-report-list-row"><span>No hay productos con stock bajo.</span><b>✓</b></div>';const or=document.getElementById('caOrderReport');if(or){const statuses=['Pendiente','En proceso','Listo','Entregado','Cancelado'];or.innerHTML=statuses.map(s=>`<div class="ca-report-list-row"><span>${s}</span><b>${x.orders.filter(o=>o.status===s).length}</b></div>`).join('')}}
function showReports(){ensureReportSection();document.querySelectorAll('.section').forEach(s=>s.classList.toggle('active',s.id==='reportes'));document.querySelectorAll('.nav button,.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.section==='reportes'));const t=document.getElementById('pageTitle'),p=document.getElementById('pageSubtitle');if(t)t.textContent='Reportes';if(p)p.textContent='Ventas, pedidos, stock y rentabilidad en un solo lugar.';renderReports();window.scrollTo({top:0,behavior:'smooth'})}
function boot(){addStyles();ensureReportNav();ensureReportSection();quickActions();renderReports();setInterval(()=>{quickActions();renderReports()},3000)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(boot,80));else setTimeout(boot,80);window.casaAllegraReports={showReports,render:renderReports};
})();
