'use client'
import {useState} from 'react'
const money=(v:number)=>new Intl.NumberFormat('es-AR',{style:'currency',currency:'ARS',maximumFractionDigits:2}).format(v||0)
type Cost={name:string;amount:number}
const ITEMS=['Luz','Gas','Internet','Teléfono','Alquiler','Obra social','Colegio','Impuestos','Seguro','Mantenimiento','Otros']
export default function CostosFijos(){const [costs,setCosts]=useState<Cost[]>(ITEMS.map(name=>({name,amount:0})));const [name,setName]=useState('');const [amount,setAmount]=useState('');const total=costs.reduce((a,c)=>a+c.amount,0);const add=()=>{const n=Number(amount);if(name.trim()&&n>=0){setCosts([...costs,{name:name.trim(),amount:n}]);setName('');setAmount('')}};return <main style={{minHeight:'100vh',background:'#f6f3ef',fontFamily:'Arial,sans-serif',padding:28,color:'#292522'}}><div style={{maxWidth:900,margin:'auto'}}><div style={{fontWeight:800,fontSize:24}}>CASA ALLEGRA APP</div><h1>🏠 Costos fijos mensuales</h1><p>Configurá los gastos mensuales que querés considerar al calcular tus precios. Todos comienzan en $0.</p><section style={card}><h2>Gastos mensuales</h2>{costs.map((c,i)=><div key={i} style={row}><span>{c.name}</span><input style={input} type="number" min="0" value={c.amount} onChange={e=>setCosts(costs.map((x,j)=>j===i?{...x,amount:Number(e.target.value)||0}:x))}/></div>)}<div style={{display:'grid',gridTemplateColumns:'1fr 180px 120px',gap:10,marginTop:18}}><input style={input} placeholder="Nuevo costo" value={name} onChange={e=>setName(e.target.value)}/><input style={input} type="number" min="0" placeholder="Importe" value={amount} onChange={e=>setAmount(e.target.value)}/><button style={button} onClick={add}>Agregar</button></div><div style={{marginTop:22,fontSize:22}}>Total mensual: <b>{money(total)}</b></div></section></div></main>}
const card:React.CSSProperties={background:'#fff',border:'1px solid #e4ddd6',borderRadius:18,padding:22,boxShadow:'0 4px 18px #00000008'}
const input:React.CSSProperties={padding:11,border:'1px solid #d8d0c8',borderRadius:10,fontSize:15,width:'100%',boxSizing:'border-box'}
const button:React.CSSProperties={padding:11,border:0,borderRadius:10,background:'#292522',color:'#fff',cursor:'pointer'}
const row:React.CSSProperties={display:'grid',gridTemplateColumns:'1fr 180px',gap:18,alignItems:'center',padding:'10px 0',borderBottom:'1px solid #eee5de'}
