'use client'
import {useMemo,useState} from 'react'
const money=(v:number)=>new Intl.NumberFormat('es-AR',{style:'currency',currency:'ARS',maximumFractionDigits:2}).format(v||0)
type Cost={name:string;amount:number}
type SectionProps={id:string;title:string;icon:string;children:React.ReactNode;openId:string;setOpenId:(id:string)=>void}
function Icon({name,size=20}:{name:string,size?:number}){const p:Record<string,React.ReactNode>={calculator:<><rect x="5" y="3" width="14" height="18" rx="2"/><path d="M8 7h8M8 11h2M14 11h2M8 15h2M14 15h2M8 19h8"/></>,box:<><path d="m12 3 8 4.5v9L12 21l-8-4.5v-9L12 3Z"/><path d="m4 7.5 8 4.5 8-4.5M12 12v9"/></>,work:<><rect x="4" y="7" width="16" height="12" rx="2"/><path d="M9 7V5h6v2M4 12h16M10 12v2h4v-2"/></>,tools:<><path d="m14.5 6.5 3-3 3 3-3 3"/><path d="m16 8-9.5 9.5a2.1 2.1 0 0 1-3-3L13 5"/><path d="m6 19 2 2"/></>,home:<><path d="m3 10 9-7 9 7"/><path d="M5 9v11h14V9M9 20v-6h6v6"/></>,money:<><rect x="3" y="6" width="18" height="12" rx="2"/><circle cx="12" cy="12" r="3"/><path d="M7 9h.01M17 15h.01"/></>,chart:<><path d="M4 19V5M4 19h17"/><path d="m7 15 4-5 3 3 5-7"/></>};return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{p[name]||p.calculator}</svg>}
function Section({id,title,icon,children,openId,setOpenId}:SectionProps){const open=openId===id;return <section style={details}><button type="button" onClick={()=>setOpenId(open?'':id)} aria-expanded={open} style={summary}><span style={{display:'flex',alignItems:'center',gap:10}}><span style={iconBox}><Icon name={icon}/></span>{title}</span><span style={{fontSize:18,color:'#64727d'}}>{open?'−':'+'}</span></button>{open&&<div style={{padding:'0 0 18px'}}>{children}</div>}</section>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label style={{display:'grid',gap:6,marginBottom:12,fontWeight:600}}>{label}{children}</label>}
const card:React.CSSProperties={background:'#fff',border:'1px solid #e4ebef',borderRadius:18,padding:22,boxShadow:'0 8px 24px rgba(52,74,87,.06)'}
const input:React.CSSProperties={padding:11,border:'1px solid #d8e1e6',borderRadius:10,fontSize:15,width:'100%',boxSizing:'border-box',outline:'none'}
const button:React.CSSProperties={padding:11,border:0,borderRadius:10,background:'#2f7f83',color:'#fff',cursor:'pointer',fontWeight:750}
const result:React.CSSProperties={display:'flex',justifyContent:'space-between',gap:15,padding:'13px 0',borderBottom:'1px solid #edf0f2'}
const details:React.CSSProperties={background:'#fff',border:'1px solid #e4ebef',borderRadius:16,padding:'0 18px',marginBottom:12,overflow:'hidden',boxShadow:'0 6px 20px rgba(52,74,87,.04)'}
const summary:React.CSSProperties={width:'100%',background:'transparent',border:0,cursor:'pointer',display:'flex',justifyContent:'space-between',alignItems:'center',fontWeight:800,fontSize:17,padding:'17px 0',color:'#293640',textAlign:'left'}
const iconBox:React.CSSProperties={width:34,height:34,borderRadius:10,display:'grid',placeItems:'center',background:'#e8f7f6',color:'#3d999c',flexShrink:0}
export default function Costos(){
 const [openId,setOpenId]=useState('');const [product,setProduct]=useState('');const [purchase,setPurchase]=useState('0');const [units,setUnits]=useState('0');const [hours,setHours]=useState('0');const [hourValue,setHourValue]=useState('0');const [margin,setMargin]=useState('0');const [amort,setAmort]=useState('0');const [costs,setCosts]=useState<Cost[]>([]);const [costName,setCostName]=useState('');const [costAmount,setCostAmount]=useState('0')
 const fixed=costs.reduce((a,c)=>a+c.amount,0),monthlyLabor=Number(hours)*Number(hourValue),totalMonthly=fixed+monthlyLabor+Number(amort)
 const r=useMemo(()=>{const p=Number(purchase),u=Number(units),h=Number(hours),hv=Number(hourValue),m=Math.min(99,Math.max(0,Number(margin)));if(p<=0||u<=0)return null;const material=p/u;const labor=(h*hv)/u;const fixedPart=(fixed+Number(amort))/u;const real=material+labor+fixedPart;const sale=real/(1-m/100);return{material,labor,fixedPart,real,sale,profit:sale-real}},[purchase,units,hours,hourValue,margin,fixed,amort])
 const addCost=()=>{const a=Number(costAmount)||0;if(costName.trim()){setCosts([...costs,{name:costName.trim(),amount:a}]);setCostName('');setCostAmount('0')}}
 return <main style={{minHeight:'100vh',background:'#f8fbfd',fontFamily:'Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif',padding:28,color:'#293640'}}><div style={{maxWidth:1100,margin:'auto'}}><header style={{marginBottom:22}}><div style={{fontWeight:900,fontSize:24,letterSpacing:'.04em',color:'#30414e'}}>CASAALLEGRA <span style={{color:'#63bfc2'}}>APP</span></div><div style={{display:'flex',alignItems:'center',gap:12,marginTop:16}}><span style={{...iconBox,width:44,height:44}}><Icon name="calculator" size={25}/></span><div><h1 style={{margin:0,fontSize:32}}>Calculadora de costos y precios</h1><p style={{margin:'7px 0 0',color:'#71808b'}}>Calculá el costo real y el precio sugerido de cada producto.</p></div></div></header>
 <Section id="producto" title="Producto y compra" icon="box" openId={openId} setOpenId={setOpenId}><Field label="Producto o insumo"><input style={input} placeholder="Escribí el producto" value={product} onChange={e=>setProduct(e.target.value)}/></Field><Field label="Costo total de compra"><input style={input} type="number" min="0" value={purchase} onChange={e=>setPurchase(e.target.value)}/></Field><Field label="Cantidad de unidades que contiene"><input style={input} type="number" min="0" value={units} onChange={e=>setUnits(e.target.value)}/></Field></Section>
 <Section id="labor" title="Mano de obra" icon="work" openId={openId} setOpenId={setOpenId}><Field label="Horas de trabajo"><input style={input} type="number" min="0" step="0.1" value={hours} onChange={e=>setHours(e.target.value)}/></Field><Field label="Valor de tu hora"><input style={input} type="number" min="0" value={hourValue} onChange={e=>setHourValue(e.target.value)}/></Field></Section>
 <Section id="amort" title="Amortización" icon="tools" openId={openId} setOpenId={setOpenId}><Field label="Amortización mensual"><input style={input} type="number" min="0" value={amort} onChange={e=>setAmort(e.target.value)}/></Field><p>Máquinas, PC, impresoras, herramientas y equipos.</p></Section>
 <Section id="fixed" title="Costos fijos mensuales" icon="home" openId={openId} setOpenId={setOpenId}><p>Agregá los costos fijos que correspondan. Todo comienza en $0.</p><div style={{display:'grid',gridTemplateColumns:'1fr 180px 120px',gap:10}}><input style={input} placeholder="Ej.: Luz" value={costName} onChange={e=>setCostName(e.target.value)}/><input style={input} type="number" min="0" value={costAmount} onChange={e=>setCostAmount(e.target.value)}/><button style={button} onClick={addCost}>Agregar</button></div>{costs.map((c,i)=><div key={i} style={result}><span>{c.name}</span><b>{money(c.amount)}</b><button style={{...button,padding:6}} onClick={()=>setCosts(costs.filter((_,j)=>j!==i))}>Eliminar</button></div>)}<div style={{marginTop:16,fontSize:18}}>Total mensual: <b>{money(fixed)}</b></div></Section>
 <Section id="profit" title="Ganancia" icon="money" openId={openId} setOpenId={setOpenId}><Field label="Margen de ganancia (%)"><input style={input} type="number" min="0" max="99" value={margin} onChange={e=>setMargin(e.target.value)}/></Field></Section>
 <Section id="result" title="Resultado" icon="chart" openId={openId} setOpenId={setOpenId}><div style={card}>{r?<>{[['Material por unidad',r.material],['Trabajo por unidad',r.labor],['Costos fijos + amortización',r.fixedPart],['Costo real por unidad',r.real],['Precio sugerido',r.sale],['Ganancia por unidad',r.profit]].map(([k,v])=><div key={String(k)} style={result}><span>{k}</span><b style={{fontSize:20}}>{money(Number(v))}</b></div>)}</>:<p>Cuando cargues costo y cantidad mayores que 0, aparecerá el cálculo.</p>}</div></Section>
 <div style={{...card,marginTop:12}}><b>Resumen mensual:</b> {money(totalMonthly)}</div></div></main>}
