'use client'
import {useMemo,useState} from 'react'
const money=(v:number)=>new Intl.NumberFormat('es-AR',{style:'currency',currency:'ARS',maximumFractionDigits:2}).format(v||0)
type Cost={name:string;amount:number}
type SectionProps={id:string;title:string;children:React.ReactNode;openId:string;setOpenId:(id:string)=>void}
function Section({id,title,children,openId,setOpenId}:SectionProps){const open=openId===id;return <section style={details}><button type="button" onClick={()=>setOpenId(open?'':id)} aria-expanded={open} style={summary}>{title}<span>{open?'⌃':'⌄'}</span></button>{open&&<div style={{padding:'0 0 18px'}}>{children}</div>}</section>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label style={{display:'grid',gap:6,marginBottom:12,fontWeight:600}}>{label}{children}</label>}
const card:React.CSSProperties={background:'#fff',border:'1px solid #e4ddd6',borderRadius:18,padding:22,boxShadow:'0 4px 18px #00000008'}
const input:React.CSSProperties={padding:11,border:'1px solid #d8d0c8',borderRadius:10,fontSize:15,width:'100%',boxSizing:'border-box'}
const button:React.CSSProperties={padding:11,border:0,borderRadius:10,background:'#292522',color:'#fff',cursor:'pointer'}
const result:React.CSSProperties={display:'flex',justifyContent:'space-between',gap:15,padding:'13px 0',borderBottom:'1px solid #eee5de'}
const details:React.CSSProperties={background:'#fff',border:'1px solid #e4ddd6',borderRadius:16,padding:'0 18px',marginBottom:12,overflow:'hidden'}
const summary:React.CSSProperties={width:'100%',background:'transparent',border:0,listStyle:'none',cursor:'pointer',display:'flex',justifyContent:'space-between',alignItems:'center',fontWeight:800,fontSize:17,padding:'17px 0',color:'#292522',textAlign:'left'}
export default function Costos(){
 const [openId,setOpenId]=useState('');const [product,setProduct]=useState('');const [purchase,setPurchase]=useState('0');const [units,setUnits]=useState('0');const [hours,setHours]=useState('0');const [hourValue,setHourValue]=useState('0');const [margin,setMargin]=useState('0');const [amort,setAmort]=useState('0');const [costs,setCosts]=useState<Cost[]>([]);const [costName,setCostName]=useState('');const [costAmount,setCostAmount]=useState('0')
 const fixed=costs.reduce((a,c)=>a+c.amount,0),monthlyLabor=Number(hours)*Number(hourValue),totalMonthly=fixed+monthlyLabor+Number(amort)
 const r=useMemo(()=>{const p=Number(purchase),u=Number(units),h=Number(hours),hv=Number(hourValue),m=Math.min(99,Math.max(0,Number(margin)));if(p<=0||u<=0)return null;const material=p/u;const labor=(h*hv)/u;const fixedPart=(fixed+Number(amort))/u;const real=material+labor+fixedPart;const sale=real/(1-m/100);return{material,labor,fixedPart,real,sale,profit:sale-real}},[purchase,units,hours,hourValue,margin,fixed,amort])
 const addCost=()=>{const a=Number(costAmount)||0;if(costName.trim()){setCosts([...costs,{name:costName.trim(),amount:a}]);setCostName('');setCostAmount('0')}}
 return <main style={{minHeight:'100vh',background:'#f6f3ef',fontFamily:'Arial,sans-serif',padding:28,color:'#292522'}}><div style={{maxWidth:1100,margin:'auto'}}><header style={{marginBottom:22}}><div style={{fontWeight:800,fontSize:24}}>CASA ALLEGRA APP</div><h1>🧮 Calculadora de costos y precios</h1><p>Cargá cada producto desde cero. Tocá una categoría para abrirla; al abrir otra, la anterior se cierra.</p></header>
 <Section id="producto" title="📦 Producto y compra" openId={openId} setOpenId={setOpenId}><Field label="Producto o insumo"><input style={input} placeholder="Escribí el producto" value={product} onChange={e=>setProduct(e.target.value)}/></Field><Field label="Costo total de compra"><input style={input} type="number" min="0" value={purchase} onChange={e=>setPurchase(e.target.value)}/></Field><Field label="Cantidad de unidades que contiene"><input style={input} type="number" min="0" value={units} onChange={e=>setUnits(e.target.value)}/></Field></Section>
 <Section id="labor" title="👷 Mano de obra" openId={openId} setOpenId={setOpenId}><Field label="Horas de trabajo"><input style={input} type="number" min="0" step="0.1" value={hours} onChange={e=>setHours(e.target.value)}/></Field><Field label="Valor de tu hora"><input style={input} type="number" min="0" value={hourValue} onChange={e=>setHourValue(e.target.value)}/></Field></Section>
 <Section id="amort" title="🔧 Amortización" openId={openId} setOpenId={setOpenId}><Field label="Amortización mensual"><input style={input} type="number" min="0" value={amort} onChange={e=>setAmort(e.target.value)}/></Field><p>Máquinas, PC, impresoras, herramientas y equipos.</p></Section>
 <Section id="fixed" title="🏠 Costos fijos mensuales" openId={openId} setOpenId={setOpenId}><p>Agregá los costos fijos que correspondan. Todo comienza en $0.</p><div style={{display:'grid',gridTemplateColumns:'1fr 180px 120px',gap:10}}><input style={input} placeholder="Ej.: Luz" value={costName} onChange={e=>setCostName(e.target.value)}/><input style={input} type="number" min="0" value={costAmount} onChange={e=>setCostAmount(e.target.value)}/><button style={button} onClick={addCost}>Agregar</button></div>{costs.map((c,i)=><div key={i} style={result}><span>{c.name}</span><b>{money(c.amount)}</b><button style={{...button,padding:6}} onClick={()=>setCosts(costs.filter((_,j)=>j!==i))}>Eliminar</button></div>)}<div style={{marginTop:16,fontSize:18}}>Total mensual: <b>{money(fixed)}</b></div></Section>
 <Section id="profit" title="💰 Ganancia" openId={openId} setOpenId={setOpenId}><Field label="Margen de ganancia (%)"><input style={input} type="number" min="0" max="99" value={margin} onChange={e=>setMargin(e.target.value)}/></Field></Section>
 <Section id="result" title="📊 Resultado" openId={openId} setOpenId={setOpenId}><div style={card}>{r?<>{[['Material por unidad',r.material],['Trabajo por unidad',r.labor],['Costos fijos + amortización',r.fixedPart],['Costo real por unidad',r.real],['Precio sugerido',r.sale],['Ganancia por unidad',r.profit]].map(([k,v])=><div key={String(k)} style={result}><span>{k}</span><b style={{fontSize:20}}>{money(Number(v))}</b></div>)}</>:<p>Cuando cargues costo y cantidad mayores que 0, aparecerá el cálculo.</p>}</div></Section>
 <div style={{...card,marginTop:12}}><b>Resumen mensual:</b> {money(totalMonthly)}</div></div></main>}
