'use client'

import { FormEvent, ReactNode, useEffect, useMemo, useState } from 'react'
import { createClient } from '@supabase/supabase-js'

type Product = { id:number; name:string; category:string; price:number; stock:number; sku:string; barcode?:string; description?:string; cost:number; minStock:number; unit:string; supplier?:string; active:boolean; catalog:boolean; image?:string }
type Sale = { id:number; date:string; product:string; amount:number; quantity:number; payment:string }
type Client = { id:number; name:string; contact:string }
type Order = { id:number; client:string; detail:string; status:string; amount:number; date:string }
type CashMove = { id:number; type:'ingreso'|'egreso'; detail:string; amount:number; date:string }
type Section = 'inicio'|'ventas'|'productos'|'clientes'|'caja'|'pedidos'|'reportes'|'integraciones'|'notificaciones'|'ia'|'ayuda'|'configuracion'

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL
const supabaseKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY
const supabase = supabaseUrl && supabaseKey ? createClient(supabaseUrl, supabaseKey) : null
const money = (v:number) => new Intl.NumberFormat('es-AR',{style:'currency',currency:'ARS',maximumFractionDigits:0}).format(v)
const load = <T,>(key:string,fallback:T):T => { try { const v=localStorage.getItem(key); return v ? JSON.parse(v) : fallback } catch { return fallback } }
const save = (key:string,value:unknown) => { try { localStorage.setItem(key,JSON.stringify(value)) } catch {} }
const generateSku = (items:Product[]) => { let n=1; let sku=''; do { sku=`SKU-${String(n).padStart(6,'0')}`; n++ } while(items.some(p=>(p.sku||'').toLowerCase()===sku.toLowerCase())); return sku }
function Icon({name,size=20}:{name:string,size?:number}) { const paths:Record<string,ReactNode>={home:<><path d="m3 10 9-7 9 7"/><path d="M5 9v11h14V9"/><path d="M9 20v-6h6v6"/></>,products:<><rect x="4" y="4" width="16" height="16" rx="2"/><path d="M8 8h8M8 12h8M8 16h5"/></>,sales:<><path d="M6 7h13l-1 8H8L6 4H3"/><circle cx="9" cy="19" r="1.5"/><circle cx="17" cy="19" r="1.5"/></>,clients:<><circle cx="12" cy="8" r="3"/><path d="M5 20c.8-3.5 3.1-5 7-5s6.2 1.5 7 5"/></>,orders:<><rect x="4" y="4" width="16" height="16" rx="2"/><path d="M8 8h8M8 12h8M8 16h5"/></>,cash:<><rect x="3" y="6" width="18" height="12" rx="2"/><circle cx="12" cy="12" r="3"/></>,reports:<><path d="M4 19V5M4 19h17"/><path d="m7 15 4-5 3 3 5-7"/></>,integrations:<><path d="M10 13a5 5 0 0 0 7.1.1l1.8-1.8a5 5 0 0 0-7.1-7.1L10 6"/><path d="M14 11a5 5 0 0 0-7.1-.1l-1.8 1.8a5 5 0 0 0 7.1 7.1L14 18"/></>,bell:<><path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9"/><path d="M10 21h4"/></>,ai:<><path d="M12 3 14 8l5 2-5 2-2 5-2-5-5-2 5-2 2-5Z"/></>,settings:<><path d="M12 3v3M12 18v3M3 12h3M18 12h3M5.6 5.6l2.1 2.1M16.3 16.3l2.1 2.1M18.4 5.6l-2.1 2.1M7.7 16.3l-2.1 2.1"/><circle cx="12" cy="12" r="4"/></>,help:<><circle cx="12" cy="12" r="9"/></>,plus:<><path d="M12 5v14M5 12h14"/></>,calculator:<><rect x="5" y="3" width="14" height="18" rx="2"/><path d="M8 7h8"/></>,arrow:<><path d="M5 12h14M13 6l6 6-6 6"/></>,logout:<><path d="M10 17l5-5-5-5M15 12H3"/><path d="M13 4h6v16h-6"/></>}; return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">{paths[name]||paths.products}</svg> }

export default function Home(){
 const [section,setSection]=useState<Section>('inicio'); const [authMode,setAuthMode]=useState<'login'|'signup'|null>(null); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [confirmPassword,setConfirmPassword]=useState(''); const [businessNameInput,setBusinessNameInput]=useState(''); const [businessName,setBusinessName]=useState(''); const [userEmail,setUserEmail]=useState(''); const [authMessage,setAuthMessage]=useState(''); const [notice,setNotice]=useState(''); const [loading,setLoading]=useState(false); const [products,setProducts]=useState<Product[]>([]); const [sales,setSales]=useState<Sale[]>([]); const [clients,setClients]=useState<Client[]>([]); const [orders,setOrders]=useState<Order[]>([]); const [cash,setCash]=useState<CashMove[]>([]); const [search,setSearch]=useState(''); const [category,setCategory]=useState('Todas'); const [assistant,setAssistant]=useState(''); const [businessCategories,setBusinessCategories]=useState<string[]>(['General','Productos','Servicios','Otros']);
 const key=userEmail.toLowerCase().trim(); const base=`casa-allegra-${key||'guest'}`;
 useEffect(()=>{if(!userEmail)return;setProducts(load(`${base}-products`,[]));setSales(load(`${base}-sales`,[]));setClients(load(`${base}-clients`,[]));setOrders(load(`${base}-orders`,[]));setCash(load(`${base}-cash`,[]));setBusinessCategories(load(`${base}-categories`,['General','Productos','Servicios','Otros']));const stored=load(`${base}-business`,'');if(stored)setBusinessName(stored)},[userEmail,base]);
 useEffect(()=>{if(!supabase)return;supabase.auth.getSession().then(({data})=>{const u=data.session?.user;if(u?.email){setUserEmail(u.email);const n=u.user_metadata?.business_name||u.user_metadata?.full_name||load(`casa-allegra-business-${u.email.toLowerCase().trim()}`,'');if(n)setBusinessName(n)}});const {data}=supabase.auth.onAuthStateChange((_event,session)=>{const u=session?.user;setUserEmail(u?.email||'');const n=u?.user_metadata?.business_name||u?.user_metadata?.full_name||'';if(n){setBusinessName(n);if(u?.email)save(`casa-allegra-business-${u.email.toLowerCase().trim()}`,n)}});return()=>data.subscription.unsubscribe()},[]);
 useEffect(()=>{if(!userEmail&&section!=='inicio')setSection('inicio')},[userEmail,section]); useEffect(()=>save(`${base}-products`,products),[base,products]); useEffect(()=>save(`${base}-sales`,sales),[base,sales]); useEffect(()=>save(`${base}-clients`,clients),[base,clients]); useEffect(()=>save(`${base}-orders`,orders),[base,orders]); useEffect(()=>save(`${base}-cash`,cash),[base,cash]); useEffect(()=>save(`${base}-categories`,businessCategories),[base,businessCategories]); useEffect(()=>{if(businessName)save(`${base}-business`,businessName)},[base,businessName]);
 const openAuth=(mode:'login'|'signup')=>{setAuthMode(mode);setAuthMessage('');setEmail('');setPassword('');setConfirmPassword('');setBusinessNameInput('')}; const goTo=(next:Section)=>{if(!userEmail){setNotice('Iniciá sesión para usar las herramientas de CASA ALLEGRA APP.');openAuth('login');return}setSection(next)}; const signOut=async()=>{if(supabase)await supabase.auth.signOut();setUserEmail('');setBusinessName('');setSection('inicio');setNotice('Sesión cerrada.')};
 const submitAuth=async(e:FormEvent)=>{e.preventDefault();setAuthMessage('');if(!email||!password||(authMode==='signup'&&!businessNameInput.trim())){setAuthMessage('Completá todos los campos.');return}if(password.length<6){setAuthMessage('La contraseña debe tener al menos 6 caracteres.');return}if(authMode==='signup'&&password!==confirmPassword){setAuthMessage('Las contraseñas no coinciden.');return}if(!supabase){setAuthMessage('La conexión de cuenta no está configurada.');return}setLoading(true);try{if(authMode==='signup'){const clean=businessNameInput.trim();const {data,error}=await supabase.auth.signUp({email:email.trim(),password,options:{data:{business_name:clean,full_name:clean},emailRedirectTo:`${window.location.origin}/?confirmado=1`}});if(error)throw error;save(`casa-allegra-business-${email.trim().toLowerCase()}`,clean);if(data.session){setUserEmail(email.trim());setBusinessName(clean);setAuthMode(null);setSection('inicio')}else setAuthMessage('Cuenta creada. Revisá tu correo para confirmar la cuenta.')}else{const {data,error}=await supabase.auth.signInWithPassword({email:email.trim(),password});if(error)throw error;const clean=data.user?.user_metadata?.business_name||data.user?.user_metadata?.full_name||load(`casa-allegra-business-${email.trim().toLowerCase()}`,'');setUserEmail(data.user?.email||email.trim());setBusinessName(clean);setAuthMode(null);setSection('inicio')}}catch(err){setAuthMessage(err instanceof Error?err.message:'No pudimos completar la operación. Intentá nuevamente.')}finally{setLoading(false)}};
 const categories=useMemo(()=>['Todas',...Array.from(new Set([...businessCategories,...products.map(p=>p.category)]))],[businessCategories,products]); const visible=useMemo(()=>products.filter(p=>(category==='Todas'||p.category===category)&&(p.name.toLowerCase().includes(search.toLowerCase())||(p.sku||'').toLowerCase().includes(search.toLowerCase()))),[products,category,search]); const today=Date.now(); const todaySales=sales.filter(s=>today-new Date(s.date).getTime()<86400000).reduce((a,s)=>a+s.amount,0); const monthSales=sales.filter(s=>{const d=new Date(s.date),n=new Date();return d.getMonth()===n.getMonth()&&d.getFullYear()===n.getFullYear()}).reduce((a,s)=>a+s.amount,0); const lowStock=products.filter(p=>p.stock<=(p.minStock??5)).length; const balance=cash.reduce((a,m)=>a+(m.type==='ingreso'?m.amount:-m.amount),0);
 const createCategory=()=>{const name=window.prompt('Nombre de la nueva categoría');const clean=name?.trim();if(!clean)return;if(!businessCategories.includes(clean))setBusinessCategories(c=>[...c,clean]);setNotice(`Categoría "${clean}" disponible.`)};
 const addProduct=(e:FormEvent)=>{e.preventDefault();const f=e.currentTarget as HTMLFormElement;const name=f.querySelector<HTMLInputElement>('[name=name]')?.value.trim()||'';const enteredSku=f.querySelector<HTMLInputElement>('[name=sku]')?.value.trim()||'';const sku=enteredSku||generateSku(products);const cost=Number(f.querySelector<HTMLInputElement>('[name=cost]')?.value||0);const price=Number(f.querySelector<HTMLInputElement>('[name=price]')?.value||0);const stock=Number(f.querySelector<HTMLInputElement>('[name=stock]')?.value||0);const minStock=Number(f.querySelector<HTMLInputElement>('[name=minStock]')?.value||0);const cat=f.querySelector<HTMLSelectElement>('[name=category]')?.value||'General';if(!name||price<=0||stock<0||cost<0){setNotice('Completá nombre, precio y stock correctamente.');return}if(products.some(p=>(p.sku||'').toLowerCase()===sku.toLowerCase())){setNotice('⚠️ SKU REPETIDO: Ese SKU ya existe. Ingresá uno diferente o dejá el campo vacío para generar uno automáticamente.');return}setProducts(p=>[...p,{id:Date.now(),name,category:cat,price,stock,sku,cost,minStock,unit:'unidad',active:true,catalog:true}]);f.reset();setNotice('Producto agregado correctamente.')};
 const registerSale=(p:Product,quantity=1,payment='Efectivo')=>{if(quantity<1||!Number.isInteger(quantity)){setNotice('La cantidad debe ser un número entero mayor a 0.');return}if(quantity>p.stock){setNotice(`Stock insuficiente. Solo hay ${p.stock} ${p.unit||'unidad'} disponibles.`);return}const total=p.price*quantity;const now=new Date().toISOString();setSales(s=>[{id:Date.now(),date:now,product:p.name,amount:total,quantity,payment},...s]);setProducts(ps=>ps.map(x=>x.id===p.id?{...x,stock:x.stock-quantity}:x));setCash(c=>[{id:Date.now()+1,type:'ingreso',detail:`Venta: ${p.name} x${quantity} · ${payment}`,amount:total,date:now},...c]);setNotice(`✅ Venta registrada: ${p.name} · ${quantity} unidad${quantity===1?'':'es'} · ${money(total)}`)};
 const addClient=(e:FormEvent)=>{e.preventDefault();const f=e.currentTarget as HTMLFormElement;const name=f.querySelector<HTMLInputElement>('[name=name]')?.value.trim()||'';const contact=f.querySelector<HTMLInputElement>('[name=contact]')?.value.trim()||'';if(!name){setNotice('Ingresá el nombre del cliente.');return}setClients(c=>[...c,{id:Date.now(),name,contact}]);f.reset();setNotice('Cliente agregado.')};
 const addOrder=(e:FormEvent)=>{e.preventDefault();const f=e.currentTarget as HTMLFormElement;const client=f.querySelector<HTMLInputElement>('[name=client]')?.value.trim()||'';const detail=f.querySelector<HTMLInputElement>('[name=detail]')?.value.trim()||'';const amount=Number(f.querySelector<HTMLInputElement>('[name=amount]')?.value||0);if(!client||!detail||amount<=0){setNotice('Completá cliente, detalle e importe.');return}setOrders(o=>[{id:Date.now(),client,detail,status:'Pendiente',amount,date:new Date().toISOString()},...o]);f.reset();setNotice('Pedido creado.')};
 const addCash=(type:'ingreso'|'egreso')=>(e:FormEvent)=>{e.preventDefault();const f=e.currentTarget as HTMLFormElement;const detail=f.querySelector<HTMLInputElement>('[name=detail]')?.value.trim()||'';const amount=Number(f.querySelector<HTMLInputElement>('[name=amount]')?.value||0);if(!detail||amount<=0){setNotice('Completá concepto e importe.');return}setCash(c=>[{id:Date.now(),type,detail,amount,date:new Date().toISOString()},...c]);f.reset();setNotice(type==='ingreso'?'Ingreso registrado.':'Egreso registrado.')};
 const askAssistant=(e:FormEvent)=>{e.preventDefault();const q=assistant.toLowerCase();let answer='Puedo ayudarte con ventas, productos, stock, clientes, pedidos, caja y reportes.';if(q.includes('stock'))answer=`Tenés ${products.length} productos cargados y ${lowStock} con stock bajo.`;else if(q.includes('venta'))answer=`Las ventas del mes suman ${money(monthSales)}.`;else if(q.includes('caja'))answer=`El saldo de caja registrado es ${money(balance)}.`;else if(q.includes('cliente'))answer=`Tenés ${clients.length} clientes registrados.`;setNotice(answer)};
 const nav:Array<[Section,string,string]>=[['inicio','Inicio','home'],['productos','Productos','products'],['ventas','Ventas','sales'],['clientes','Clientes','clients'],['pedidos','Pedidos','orders'],['caja','Caja','cash'],['reportes','Reportes','reports'],['integraciones','Integraciones','integrations'],['ia','IA Asistente','ai'],['notificaciones','Notificaciones','bell'],['configuracion','Configuración','settings'],['ayuda','Ayuda','help']];
 return <div className="app-shell"><header className="topbar"><div className="topbar-brand"><img src="/icon-512.png" alt="CASA ALLEGRA"/><span>CASA ALLEGRA <b>APP</b></span></div><div className="topbar-right"><button className="icon-btn" onClick={()=>goTo('notificaciones')}><Icon name="bell" size={20}/><span className="badge">3</span></button>{userEmail?<div className="account"><strong>{businessName||'CASA ALLEGRA'}</strong><small>Cuenta activa</small></div>:<button className="top-login" onClick={()=>openAuth('login')}>Ingresar</button>}<button className="circle-brand"><img src="/icon-512.png" alt=""/></button></div></header><div className="layout"><aside className="sidebar"><div className="sidebar-title">MI NEGOCIO</div>{nav.map(([id,label,icon])=><button key={id} onClick={()=>goTo(id)} className={`nav-item ${section===id?'active':''}`}><Icon name={icon} size={19}/><span>{label}</span></button>)}{userEmail&&<button className="nav-item logout" onClick={signOut}><Icon name="logout" size={19}/><span>Cerrar sesión</span></button>}</aside><main className="content-area">{notice&&<div className="notice">{notice}<button onClick={()=>setNotice('')}>×</button></div>}
 {section==='inicio'&&<section className="welcome-card"><div><span className="eyebrow">CASA ALLEGRA APP</span><h1>{userEmail?`¡BIENVENIDO/A ${businessName||'A CASA ALLEGRA'}!`:'¡BIENVENIDO/A A CASA ALLEGRA APP!'}</h1><p>GESTIONÁ TU NEGOCIO DE FORMA SIMPLE Y ORDENADA.</p>{!userEmail&&<button className="primary-btn" onClick={()=>openAuth('signup')}>Crear cuenta</button>}</div></section>}
 {section==='productos'&&<section className="two-col"><div className="panel"><div className="panel-heading"><div><h2>Productos</h2><small>Catálogo e inventario</small></div></div><div className="toolbar"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar por nombre o SKU..."/>{categories.map(c=><button key={c} className={`filter ${category===c?'active-filter':''}`} onClick={()=>setCategory(c)}>{c}</button>)}</div><div className="product-grid">{visible.map(p=><article className="mini-product" key={p.id}><div className="mini-art">{p.image?<img src={p.image} alt={p.name}/>:<Icon name="products" size={40}/>}</div><h3>{p.name}</h3><small>SKU {p.sku||'Sin SKU'} · {p.category}</small><small>Stock {p.stock} · Costo {money(p.cost||0)}</small><div className="mini-footer"><b>{money(p.price)}</b><button onClick={()=>goTo('ventas')}>Vender</button></div></article>)}</div></div><form className="panel form-panel" onSubmit={addProduct}><h2>Nuevo producto</h2><label>Nombre *</label><input name="name" required/><label>SKU <span style={{fontWeight:400,opacity:.7}}>(opcional)</span></label><input name="sku" placeholder="Dejá vacío para generar automáticamente"/><label>Categoría *</label><select name="category" defaultValue="General">{businessCategories.map(c=><option key={c}>{c}</option>)}</select><label>Costo</label><input name="cost" type="number" min="0"/><label>Precio de venta *</label><input name="price" type="number" min="0" required/><label>Stock actual *</label><input name="stock" type="number" min="0" required/><label>Stock mínimo</label><input name="minStock" type="number" min="0"/><button className="primary-btn"><Icon name="plus" size={17}/>Agregar producto</button></form></section>}
 {section==='ventas'&&<section className="panel large-section"><div className="panel-heading"><div><h2>Ventas</h2><small>Registrá ventas y actualizá automáticamente el stock y la caja.</small></div></div>{products.length?<div className="product-grid sale-grid">{products.map(p=><SaleCard key={p.id} product={p} onSell={registerSale}/>)}</div>:<div className="empty-state">Primero agregá productos desde Productos.</div>}<div className="table sales-history"><h3>Historial de ventas</h3>{sales.slice(0,30).map(s=><div className="trow" key={s.id}><span><b>{s.product}</b><small>{s.quantity||1} unidad{(s.quantity||1)===1?'':'es'} · {s.payment||'Efectivo'}</small></span><span>{new Date(s.date).toLocaleString('es-AR')}</span><b>{money(s.amount)}</b></div>)}{!sales.length&&<div className="empty-state">Todavía no registraste ventas.</div>}</div></section>}
 {section==='clientes'&&<section className="two-col"><div className="panel"><h2>Clientes</h2>{clients.map(c=><div className="client-row" key={c.id}><strong>{c.name}</strong><small>{c.contact}</small></div>)}{!clients.length&&<div className="empty-state">Todavía no hay clientes.</div>}</div><form className="panel form-panel" onSubmit={addClient}><h2>Nuevo cliente</h2><input name="name" placeholder="Nombre y apellido"/><input name="contact" placeholder="WhatsApp, teléfono o correo"/><button className="primary-btn">Agregar cliente</button></form></section>}
 {section==='pedidos'&&<section className="two-col"><div className="panel"><h2>Pedidos</h2>{orders.map(o=><div className="order-row" key={o.id}><div><strong>{o.client}</strong><small>{o.detail}</small></div><span>{o.status}</span><b>{money(o.amount)}</b></div>)}{!orders.length&&<div className="empty-state">Todavía no hay pedidos.</div>}</div><form className="panel form-panel" onSubmit={addOrder}><h2>Nuevo pedido</h2><input name="client" placeholder="Cliente"/><input name="detail" placeholder="Detalle del pedido"/><input name="amount" type="number" placeholder="Importe"/><button className="primary-btn">Crear pedido</button></form></section>}
 {section==='caja'&&<section className="two-col"><div className="panel"><div className="panel-heading"><h2>Caja</h2><strong>{money(balance)}</strong></div>{cash.map(m=><div className="trow" key={m.id}><span>{m.type==='ingreso'?'Ingreso':'Egreso'} · {m.detail}</span><b>{m.type==='ingreso'?'+':'-'}{money(m.amount)}</b></div>)}{!cash.length&&<div className="empty-state">No hay movimientos.</div>}</div><div className="panel"><h2>Movimientos</h2><form onSubmit={addCash('ingreso')} className="form-panel"><input name="detail" placeholder="Concepto"/><input name="amount" type="number" placeholder="Importe"/><button className="primary-btn">Registrar ingreso</button></form><form onSubmit={addCash('egreso')} className="form-panel"><input name="detail" placeholder="Concepto"/><input name="amount" type="number" placeholder="Importe"/><button className="secondary-btn">Registrar egreso</button></form></div></section>}
 {section==='reportes'&&<section className="panel large-section"><h2>Reportes</h2><div className="report-grid"><div className="report-card"><small>Ventas del mes</small><strong>{money(monthSales)}</strong></div><div className="report-card"><small>Saldo de caja</small><strong>{money(balance)}</strong></div><div className="report-card"><small>Productos</small><strong>{products.length}</strong></div><div className="report-card"><small>Pedidos</small><strong>{orders.length}</strong></div></div></section>}
 {section==='integraciones'&&<section className="panel large-section"><h2>Integraciones</h2><p>Mercado Pago, Mercado Libre, Mercado Envíos, Andreani y Correo Argentino.</p></section>}{section==='ia'&&<section className="panel large-section"><h2>IA Asistente</h2><form onSubmit={askAssistant}><input value={assistant} onChange={e=>setAssistant(e.target.value)} placeholder="Ej.: ¿cuánto vendí este mes?"/><button className="primary-btn">Consultar</button></form></section>}{section==='notificaciones'&&<section className="panel large-section"><h2>Notificaciones</h2><p>{lowStock} productos con stock bajo.</p></section>}{section==='configuracion'&&<section className="panel large-section"><h2>Configuración</h2><p>Negocio: <b>{businessName||'CASA ALLEGRA'}</b></p><p>Cuenta: <b>{userEmail}</b></p></section>}{section==='ayuda'&&<section className="panel large-section"><h2>Ayuda</h2><p>Administrá productos, ventas, clientes, pedidos, caja y reportes.</p></section>}
 </main></div><footer className="footer">CASA ALLEGRA APP · Gestión de negocios</footer>{authMode&&<div className="auth-overlay" onClick={()=>setAuthMode(null)}><form className="auth-modal" onSubmit={submitAuth} onClick={e=>e.stopPropagation()}><button type="button" className="modal-close" onClick={()=>setAuthMode(null)}>×</button><span className="eyebrow">CASA ALLEGRA APP</span><h2>{authMode==='login'?'Ingresá a tu cuenta':'Creá la cuenta de tu negocio'}</h2>{authMode==='signup'&&<><label>Nombre del negocio</label><input value={businessNameInput} onChange={e=>setBusinessNameInput(e.target.value)} placeholder="Ej.: CASA ALLEGRA"/></>}<label>Correo electrónico</label><input value={email} onChange={e=>setEmail(e.target.value)} type="email"/><label>Contraseña</label><input value={password} onChange={e=>setPassword(e.target.value)} type="password"/>{authMode==='signup'&&<><label>Repetir contraseña</label><input value={confirmPassword} onChange={e=>setConfirmPassword(e.target.value)} type="password"/></>}{authMessage&&<div className="auth-message">{authMessage}</div>}<button className="primary-btn full" disabled={loading}>{loading?'Procesando…':authMode==='login'?'Ingresar':'Crear cuenta'}</button></form></div>}</div>
}

function SaleCard({product,onSell}:{product:Product;onSell:(p:Product,q:number,payment:string)=>void}){const [quantity,setQuantity]=useState(1);const [payment,setPayment]=useState('Efectivo');const total=product.price*quantity;const max=product.stock;return <article className="mini-product sale-card"><div className="mini-art">{product.image?<img src={product.image} alt={product.name}/>:<Icon name="sales" size={36}/>}</div><h3>{product.name}</h3><small>SKU {product.sku||'Sin SKU'} · Stock disponible: <b>{product.stock}</b></small><div className="sale-controls"><label>Cantidad<input type="number" min="1" max={max||1} value={quantity} onChange={e=>setQuantity(Math.max(1,Math.min(max||1,Number(e.target.value)||1)))} disabled={!max}/></label><label>Medio de pago<select value={payment} onChange={e=>setPayment(e.target.value)}><option>Efectivo</option><option>Transferencia</option><option>Mercado Pago</option><option>Tarjeta</option><option>Otro</option></select></label></div><div className="sale-total"><span>Total</span><b>{money(total)}</b></div><button className="primary-btn" onClick={()=>onSell(product,quantity,payment)} disabled={!product.stock||product.active===false}>REGISTRAR VENTA</button></article>}
