'use client'
import { FormEvent, useMemo, useState } from 'react'

type Client = { id:number; name:string; contact:string; phone?:string; email?:string; address?:string; notes?:string; dni?:string; cuil?:string }
type Product = { id:number; name:string; price:number; stock:number; sku:string; active?:boolean }
type OrderItem = { productId:number; name:string; quantity:number; unitPrice:number; total:number }
type Order = { id:number; number?:string; clientId?:number; client:string; items?:OrderItem[]; detail:string; status:string; amount:number; discount?:number; payment?:string; date:string; deliveryDate?:string; notes?:string }
type Props = { clients:Client[]; products:Product[]; orders:Order[]; onClientsChange:(clients:Client[])=>void; onOrdersChange:(orders:Order[])=>void; onNotice:(message:string)=>void }
const money=(v:number)=>new Intl.NumberFormat('es-AR',{style:'currency',currency:'ARS',maximumFractionDigits:0}).format(v)
const statuses=['Pendiente','En producción','Listo','Entregado','Cancelado']
const statusMeta:(Record<string,{icon:string;label:string;bg:string;fg:string}>)={
 'Pendiente':{icon:'🕒',label:'PENDIENTE',bg:'#FFF4CC',fg:'#8A6500'},
 'En producción':{icon:'🛠️',label:'EN PRODUCCIÓN',bg:'#E7D9FF',fg:'#6842A5'},
 'Listo':{icon:'✅',label:'LISTO',bg:'#D8F6EA',fg:'#176B4D'},
 'Entregado':{icon:'📦',label:'ENTREGADO',bg:'#D8ECFF',fg:'#175A8A'},
 'Cancelado':{icon:'✕',label:'CANCELADO',bg:'#FFE0E0',fg:'#9B2C2C'}
}
export default function OrderManager({clients,products,orders,onClientsChange,onOrdersChange,onNotice}:Props){
 const [editing,setEditing]=useState<Order|null>(null); const [viewing,setViewing]=useState<Order|null>(null); const [clientId,setClientId]=useState<number|null>(null); const [newClient,setNewClient]=useState(false); const [items,setItems]=useState<OrderItem[]>([]); const [productId,setProductId]=useState<number|null>(null); const [qty,setQty]=useState(1); const [discountInput,setDiscountInput]=useState(''); const [payment,setPayment]=useState('A definir'); const [deliveryDate,setDeliveryDate]=useState(''); const [notes,setNotes]=useState(''); const [query,setQuery]=useState('')
 const filtered=useMemo(()=>orders.filter(o=>`${o.number||'PED-'+o.id} ${o.client} ${o.detail} ${o.status}`.toLowerCase().includes(query.toLowerCase())),[orders,query])
 const subtotal=items.reduce((a,i)=>a+i.total,0); const discount=discountInput===''?0:Math.max(0,Number(discountInput)||0); const total=Math.max(0,subtotal-discount)
 const addItem=()=>{const p=products.find(x=>x.id===productId);if(!p||qty<1)return;const existing=items.find(i=>i.productId===p.id);const newQty=(existing?.quantity||0)+qty;if(newQty>p.stock){onNotice(`Stock insuficiente para ${p.name}. Disponible: ${p.stock}.`);return}setItems(existing?items.map(i=>i.productId===p.id?{...i,quantity:newQty,total:newQty*i.unitPrice}:i):[...items,{productId:p.id,name:p.name,quantity:qty,unitPrice:p.price,total:qty*p.price}]);setProductId(null);setQty(1)}
 const createInlineClient=(name:string,contact:string)=>{const id=Date.now();const c={id,name,contact};onClientsChange([c,...clients]);setClientId(id);setNewClient(false);onNotice(`Cliente ${name} creado y seleccionado.`)}
 const reset=()=>{setEditing(null);setClientId(null);setItems([]);setProductId(null);setQty(1);setDiscountInput('');setPayment('A definir');setDeliveryDate('');setNotes('')}
 const saveOrder=(e:FormEvent)=>{e.preventDefault();if(!clientId){onNotice('Seleccioná un cliente.');return}if(!items.length){onNotice('Agregá al menos un producto al pedido.');return}if(deliveryDate){const today=new Date();today.setHours(0,0,0,0);const chosen=new Date(deliveryDate+'T00:00:00');if(chosen<today){onNotice('⚠️ La fecha de entrega ya pasó. Elegí hoy o una fecha futura.');return}}const client=clients.find(c=>c.id===clientId);if(!client){onNotice('El cliente seleccionado no existe.');return}const next={id:editing?.id||Date.now(),number:editing?.number||`PED-${new Date().getFullYear()}-${String(orders.length+1).padStart(4,'0')}`,clientId,client:client.name,items,detail:items.map(i=>`${i.name} x${i.quantity}`).join(', '),status:editing?.status||'Pendiente',amount:total,discount,payment:payment||'A definir',date:editing?.date||new Date().toISOString(),deliveryDate,notes};onOrdersChange(editing?orders.map(o=>o.id===editing.id?next:o):[next,...orders]);reset();onNotice(editing?'Pedido actualizado correctamente.':'Pedido creado correctamente.')}
 const startEdit=(o:Order)=>{setEditing(o);setClientId(o.clientId||clients.find(c=>c.name.toLowerCase()===o.client.toLowerCase())?.id||null);setItems(o.items||[]);setDiscountInput(o.discount?String(o.discount):'');setPayment(o.payment||'A definir');setDeliveryDate(o.deliveryDate||'');setNotes(o.notes||'')}
 const changeStatus=(o:Order,status:string)=>{const next={...o,status};onOrdersChange(orders.map(x=>x.id===o.id?next:x));setViewing(next);onNotice(`Estado actualizado: ${status}.`)}
 const remove=(o:Order)=>{if(!window.confirm(`¿Eliminar el pedido ${o.number||'PED-'+o.id}?`))return;onOrdersChange(orders.filter(x=>x.id!==o.id));if(viewing?.id===o.id)setViewing(null);onNotice('Pedido eliminado.')}
 const meta=(status:string)=>statusMeta[status]||{icon:'•',label:status.toUpperCase(),bg:'#EEEEEE',fg:'#444444'}
 return <>
 <section className="two-col"><div className="panel"><div className="panel-heading"><div><h2>Pedidos</h2><small>{orders.length} pedido{orders.length===1?'':'s'}</small></div><button className="secondary-btn" type="button" onClick={()=>setQuery('')}>Limpiar búsqueda</button></div><div className="toolbar"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="🔎 Buscar por número, cliente o estado..."/></div>
 <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(135px,1fr))',gap:10,marginBottom:14}}>{statuses.map(s=>{const count=orders.filter(o=>o.status===s).length;const m=meta(s);return <button key={s} type="button" onClick={()=>setQuery(s)} style={{border:'1px solid #E5E7EB',borderRadius:12,padding:'10px 12px',textAlign:'left',background:'#FFF',cursor:'pointer'}}><div style={{fontSize:12,fontWeight:800,color:m.fg}}>{m.icon} {m.label}</div><strong style={{fontSize:22}}>{count}</strong><small style={{display:'block',opacity:.65}}>pedidos</small></button>})}</div>
 <div className="client-list">{filtered.map(o=>{const m=meta(o.status);return <div className="order-row" key={o.id} style={{cursor:'pointer',display:'flex',alignItems:'center',gap:12}} onClick={()=>setViewing(o)}><div style={{minWidth:0,flex:1}}><strong>{o.number||`PED-${o.id}`} · {o.client}</strong><small>{o.detail}</small><small>Entrega: {o.deliveryDate||'Sin fecha'}</small></div><span style={{display:'inline-flex',alignItems:'center',gap:6,padding:'8px 12px',borderRadius:999,fontWeight:900,fontSize:12,background:m.bg,color:m.fg,whiteSpace:'nowrap'}}>{m.icon} {m.label}</span><b>{money(o.amount)}</b></div>})}{!filtered.length&&<div className="empty-state">{orders.length?'No encontramos pedidos.':'Todavía no hay pedidos.'}</div>}</div></div>
 <form className="panel form-panel" onSubmit={saveOrder}><h2>{editing?'Editar pedido':'Nuevo pedido'}</h2><label>Cliente *</label><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><select value={clientId??''} onChange={e=>setClientId(e.target.value?Number(e.target.value):null)} style={{flex:1,minWidth:220}}><option value="">Seleccionar cliente...</option>{clients.map(c=><option key={c.id} value={c.id}>{c.name}{c.contact?` · ${c.contact}`:''}</option>)}</select><button type="button" className="secondary-btn" onClick={()=>setNewClient(v=>!v)}>＋ Nuevo cliente</button></div>{newClient&&<div className="panel" style={{marginTop:10}}><label>Nombre y apellido *</label><input id="orderNewClientName" placeholder="Ej.: María González"/><label>WhatsApp / teléfono</label><input id="orderNewClientContact" placeholder="Ej.: 11 1234-5678"/><button type="button" className="primary-btn" onClick={()=>{const n=(document.getElementById('orderNewClientName') as HTMLInputElement)?.value.trim()||'';const c=(document.getElementById('orderNewClientContact') as HTMLInputElement)?.value.trim()||'';if(!n){onNotice('Ingresá el nombre del cliente.');return}createInlineClient(n,c)}}>Crear y seleccionar</button></div>}
 <label>Productos *</label><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><select value={productId??''} onChange={e=>setProductId(e.target.value?Number(e.target.value):null)} style={{flex:1,minWidth:220}}><option value="">Seleccionar producto...</option>{products.filter(p=>p.active!==false).map(p=><option key={p.id} value={p.id}>{p.name} · {money(p.price)} · Stock {p.stock}</option>)}</select><input type="number" min="1" value={qty} onChange={e=>setQty(Math.max(1,Number(e.target.value)||1))} style={{width:90}}/><button type="button" className="secondary-btn" onClick={addItem}>Agregar</button></div>{items.length>0&&<div className="table" style={{marginTop:10}}>{items.map(i=><div className="trow" key={i.productId}><span>{i.name} <small>{i.quantity} × {money(i.unitPrice)}</small></span><b>{money(i.total)}</b><button type="button" className="secondary-btn" onClick={()=>setItems(items.filter(x=>x.productId!==i.productId))}>Quitar</button></div>)}</div>}
 <div className="two-col"><div><label>Descuento</label><input type="number" min="0" step="1" value={discountInput} onChange={e=>setDiscountInput(e.target.value)} placeholder="0"/><small>Dejá vacío o 0 si no hay descuento. El total se actualiza automáticamente.</small></div><div><label>Medio de pago</label><select value={payment} onChange={e=>setPayment(e.target.value)}><option>A definir</option><option>Efectivo</option><option>Transferencia</option><option>Mercado Pago</option><option>Tarjeta</option><option>Otro</option></select></div></div><label>Fecha estimada de entrega</label><input type="date" min={new Date().toISOString().slice(0,10)} value={deliveryDate} onChange={e=>setDeliveryDate(e.target.value)}/><label>Observaciones</label><textarea rows={3} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Detalles especiales del pedido..."/><div className="panel-heading"><div><small>Subtotal: {money(subtotal)} · Descuento: {money(discount)}</small><strong>Total: {money(total)}</strong></div><button className="primary-btn">{editing?'Guardar cambios':'Crear pedido'}</button></div></form></section>
 {viewing&&<div className="auth-overlay" onClick={()=>setViewing(null)}><div className="auth-modal" onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setViewing(null)}>×</button><span className="eyebrow">CASA ALLEGRA APP</span><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:12}}><div><h2>{viewing.number||`PED-${viewing.id}`}</h2><p style={{margin:'4px 0 0'}}>{viewing.client}</p></div><span style={{display:'inline-flex',alignItems:'center',gap:6,padding:'9px 14px',borderRadius:999,fontWeight:900,fontSize:12,...(()=>{const m=meta(viewing.status);return {background:m.bg,color:m.fg}})()}}>{meta(viewing.status).icon} {meta(viewing.status).label}</span></div><p><b>Detalle:</b> {viewing.detail}</p><p><b>Subtotal:</b> {money((viewing.items||[]).reduce((a,i)=>a+i.total,0))}</p><p><b>Descuento:</b> {money(viewing.discount||0)} · <b>Total:</b> {money(viewing.amount)} · <b>Pago:</b> {viewing.payment||'A definir'}</p><p><b>Entrega:</b> {viewing.deliveryDate||'Sin fecha'}</p><p><b>Observaciones:</b> {viewing.notes||'Sin observaciones'}</p><label>Estado del pedido</label><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(120px,1fr))',gap:8,marginTop:8}}>{statuses.map(s=>{const m=meta(s);const active=viewing.status===s;return <button key={s} type="button" onClick={()=>changeStatus(viewing,s)} style={{padding:'10px 8px',borderRadius:12,border:active?`2px solid ${m.fg}`:'1px solid #E5E7EB',background:active?m.bg:'#FFF',color:active?m.fg:'#444',fontWeight:900,cursor:'pointer'}}>{m.icon} {m.label}</button>})}</div><div style={{display:'flex',gap:8,flexWrap:'wrap',marginTop:14}}><button type="button" className="primary-btn" onClick={()=>{startEdit(viewing);setViewing(null)}}>✏️ Editar</button><button type="button" className="secondary-btn" onClick={()=>remove(viewing)}>🗑️ Eliminar</button>{(clients.find(c=>c.id===viewing.clientId)?.contact)&&<a className="secondary-btn" href={`https://wa.me/${(clients.find(c=>c.id===viewing.clientId)?.contact||'').replace(/\D/g,'')}`} target="_blank" rel="noreferrer">💬 WhatsApp</a>}</div></div></div>}
 </>
}
