'use client'
import { FormEvent, useMemo, useState } from 'react'

type Client = { id:number; name:string; contact:string; phone?:string; email?:string; address?:string; notes?:string; dni?:string; cuil?:string }
type Product = { id:number; name:string; price:number; stock:number; sku:string; active?:boolean }
type OrderItem = { productId:number; name:string; quantity:number; unitPrice:number; total:number }
type Order = { id:number; number:string; clientId?:number; client:string; items?:OrderItem[]; detail:string; status:string; amount:number; discount:number; payment:string; date:string; deliveryDate?:string; notes?:string }
type Props = { clients:Client[]; products:Product[]; orders:Order[]; onClientsChange:(clients:Client[])=>void; onOrdersChange:(orders:Order[])=>void; onNotice:(message:string)=>void }
const money=(v:number)=>new Intl.NumberFormat('es-AR',{style:'currency',currency:'ARS',maximumFractionDigits:0}).format(v)
const statuses=['Pendiente','En producción','Listo','Entregado','Cancelado']
export default function OrderManager({clients,products,orders,onClientsChange,onOrdersChange,onNotice}:Props){
 const [editing,setEditing]=useState<Order|null>(null); const [viewing,setViewing]=useState<Order|null>(null); const [clientId,setClientId]=useState<number|null>(null); const [newClient,setNewClient]=useState(false); const [items,setItems]=useState<OrderItem[]>([]); const [productId,setProductId]=useState<number|null>(null); const [qty,setQty]=useState(1); const [discount,setDiscount]=useState(0); const [payment,setPayment]=useState('A definir'); const [deliveryDate,setDeliveryDate]=useState(''); const [notes,setNotes]=useState(''); const [query,setQuery]=useState('')
 const filtered=useMemo(()=>orders.filter(o=>`${o.number} ${o.client} ${o.detail} ${o.status}`.toLowerCase().includes(query.toLowerCase())),[orders,query]);
 const subtotal=items.reduce((a,i)=>a+i.total,0); const total=Math.max(0,subtotal-Number(discount||0))
 const addItem=()=>{const p=products.find(x=>x.id===productId);if(!p||qty<1)return; const existing=items.find(i=>i.productId===p.id); const newQty=(existing?.quantity||0)+qty; if(newQty>p.stock){onNotice(`Stock insuficiente para ${p.name}. Disponible: ${p.stock}.`);return} setItems(existing?items.map(i=>i.productId===p.id?{...i,quantity:newQty,total:newQty*i.unitPrice}:i):[...items,{productId:p.id,name:p.name,quantity:qty,unitPrice:p.price,total:qty*p.price}]);setProductId(null);setQty(1)}
 const createInlineClient=(name:string,contact:string)=>{const id=Date.now();const c={id,name,contact};onClientsChange([c,...clients]);setClientId(id);setNewClient(false);onNotice(`Cliente ${name} creado y seleccionado.`)}
 const reset=()=>{setEditing(null);setClientId(null);setItems([]);setProductId(null);setQty(1);setDiscount(0);setPayment('A definir');setDeliveryDate('');setNotes('')}
 const saveOrder=(e:FormEvent)=>{e.preventDefault();if(!clientId){onNotice('Seleccioná un cliente.');return}if(!items.length){onNotice('Agregá al menos un producto al pedido.');return}const client=clients.find(c=>c.id===clientId);if(!client){onNotice('El cliente seleccionado no existe.');return}const f=e.currentTarget as HTMLFormElement;const order={id:editing?.id||Date.now(),number:editing?.number||`PED-${new Date().getFullYear()}-${String(orders.length+1).padStart(4,'0')}`,clientId,client:client.name,items,detail:items.map(i=>`${i.name} x${i.quantity}`).join(', '),status:editing?.status||'Pendiente',amount:total,discount:Number(discount||0),payment,date:editing?.date||new Date().toISOString(),deliveryDate,notes};onOrdersChange(editing?orders.map(o=>o.id===editing.id?order:o):[order,...orders]);reset();onNotice(editing?'Pedido actualizado correctamente.':'Pedido creado correctamente.')}
 const startEdit=(o:Order)=>{setEditing(o);setClientId(o.clientId||clients.find(c=>c.name.toLowerCase()===o.client.toLowerCase())?.id||null);setItems(o.items||[]);setDiscount(o.discount||0);setPayment(o.payment||'A definir');setDeliveryDate(o.deliveryDate||'');setNotes(o.notes||'')}
 const changeStatus=(o:Order,status:string)=>{const next={...o,status};onOrdersChange(orders.map(x=>x.id===o.id?next:x));setViewing(next)}
 const remove=(o:Order)=>{if(!window.confirm(`¿Eliminar el pedido ${o.number}?`))return;onOrdersChange(orders.filter(x=>x.id!==o.id));if(viewing?.id===o.id)setViewing(null);onNotice('Pedido eliminado.')}
 const newOrder=()=>reset()
 return <>
 <section className="two-col"><div className="panel"><div className="panel-heading"><div><h2>Pedidos</h2><small>{orders.length} pedido{orders.length===1?'':'s'}</small></div><button className="secondary-btn" type="button" onClick={()=>setQuery('')}>Limpiar búsqueda</button></div><div className="toolbar"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="🔎 Buscar por número, cliente o estado..."/></div><div className="client-list">{filtered.map(o=><div className="order-row" key={o.id} style={{cursor:'pointer'}} onClick={()=>setViewing(o)}><div><strong>{o.number} · {o.client}</strong><small>{o.detail}</small><small>Entrega: {o.deliveryDate||'Sin fecha'}</small></div><span>{o.status}</span><b>{money(o.amount)}</b></div>)}{!filtered.length&&<div className="empty-state">{orders.length?'No encontramos pedidos.':'Todavía no hay pedidos.'}</div>}</div></div>
 <form className="panel form-panel" onSubmit={saveOrder}><h2>{editing?'Editar pedido':'Nuevo pedido'}</h2><label>Cliente *</label><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><select value={clientId??''} onChange={e=>setClientId(e.target.value?Number(e.target.value):null)} style={{flex:1,minWidth:220}}><option value="">Seleccionar cliente...</option>{clients.map(c=><option key={c.id} value={c.id}>{c.name}{c.contact?` · ${c.contact}`:''}</option>)}</select><button type="button" className="secondary-btn" onClick={()=>setNewClient(v=>!v)}>＋ Nuevo cliente</button></div>{newClient&&<div className="panel" style={{marginTop:10}}><label>Nombre y apellido *</label><input id="orderNewClientName" placeholder="Ej.: María González"/><label>WhatsApp / teléfono</label><input id="orderNewClientContact" placeholder="Ej.: 11 1234-5678"/><button type="button" className="primary-btn" onClick={()=>{const n=(document.getElementById('orderNewClientName') as HTMLInputElement)?.value.trim()||'';const c=(document.getElementById('orderNewClientContact') as HTMLInputElement)?.value.trim()||'';if(!n){onNotice('Ingresá el nombre del cliente.');return}createInlineClient(n,c)}}>Crear y seleccionar</button></div>}
 <label>Productos</label><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><select value={productId??''} onChange={e=>setProductId(e.target.value?Number(e.target.value):null)} style={{flex:1,minWidth:220}}><option value="">Seleccionar producto...</option>{products.filter(p=>p.active!==false).map(p=><option key={p.id} value={p.id}>{p.name} · {money(p.price)} · Stock {p.stock}</option>)}</select><input type="number" min="1" value={qty} onChange={e=>setQty(Math.max(1,Number(e.target.value)||1))} style={{width:90}}/><button type="button" className="secondary-btn" onClick={addItem}>Agregar</button></div>{items.length>0&&<div className="table" style={{marginTop:10}}>{items.map(i=><div className="trow" key={i.productId}><span>{i.name} <small>{i.quantity} × {money(i.unitPrice)}</small></span><b>{money(i.total)}</b><button type="button" className="secondary-btn" onClick={()=>setItems(items.filter(x=>x.productId!==i.productId))}>Quitar</button></div>)}</div>}
 <div className="two-col"><div><label>Descuento</label><input type="number" min="0" value={discount} onChange={e=>setDiscount(Number(e.target.value)||0)}/></div><div><label>Medio de pago</label><select value={payment} onChange={e=>setPayment(e.target.value)}><option>A definir</option><option>Efectivo</option><option>Transferencia</option><option>Mercado Pago</option><option>Tarjeta</option><option>Otro</option></select></div></div><label>Fecha estimada de entrega</label><input type="date" value={deliveryDate} onChange={e=>setDeliveryDate(e.target.value)}/><label>Observaciones</label><textarea rows={3} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Detalles especiales del pedido..."/><div className="panel-heading"><strong>Total: {money(total)}</strong><button className="primary-btn">{editing?'Guardar cambios':'Crear pedido'}</button></div></form></section>
 {viewing&&<div className="auth-overlay" onClick={()=>setViewing(null)}><div className="auth-modal" onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setViewing(null)}>×</button><span className="eyebrow">CASA ALLEGRA APP</span><h2>{viewing.number}</h2><p><b>Cliente:</b> {viewing.client}</p><p><b>Detalle:</b> {viewing.detail}</p><p><b>Total:</b> {money(viewing.amount)} · <b>Pago:</b> {viewing.payment}</p><p><b>Entrega:</b> {viewing.deliveryDate||'Sin fecha'}</p><p><b>Observaciones:</b> {viewing.notes||'Sin observaciones'}</p><label>Estado</label><select value={viewing.status} onChange={e=>changeStatus(viewing,e.target.value)}>{statuses.map(s=><option key={s}>{s}</option>)}</select><div style={{display:'flex',gap:8,flexWrap:'wrap',marginTop:12}}><button className="primary-btn" onClick={()=>{startEdit(viewing);setViewing(null)}}>✏️ Editar</button><button className="secondary-btn" onClick={()=>remove(viewing)}>🗑️ Eliminar</button>{(clients.find(c=>c.id===viewing.clientId)?.contact)&&<a className="secondary-btn" href={`https://wa.me/${(clients.find(c=>c.id===viewing.clientId)?.contact||'').replace(/\D/g,'')}`} target="_blank" rel="noreferrer">💬 WhatsApp</a>}</div></div></div>}
 </>
}
