'use client'
import { FormEvent, useEffect, useMemo, useState } from 'react'

type Product={id:number;name:string;category:string;price:number;stock:number;sku:string;barcode?:string;description?:string;cost:number;minStock:number;unit:string;supplier?:string;active:boolean;catalog:boolean;image?:string;brand?:string}
type Client={id:number;name:string;contact:string}
type Supplier={id:number;name:string;contact:string;phone:string;email:string;address:string;cuit:string;website:string;notes:string;productIds:number[]}
type Purchase={id:number;supplierId:number;supplierName:string;date:string;payment:string;reference:string;discount:number;total:number;items:{productId:number;name:string;quantity:number;unitPrice:number;total:number}[]}
type Props={products:Product[];onProductsChange:(products:Product[])=>void;clients?:Client[];storageKey:string;onNotice:(message:string)=>void}
const money=(v:number)=>new Intl.NumberFormat('es-AR',{style:'currency',currency:'ARS',maximumFractionDigits:0}).format(v)
const read=(key:string,fallback:any)=>{try{const v=localStorage.getItem(key);return v?JSON.parse(v):fallback}catch{return fallback}}
export default function SupplierManager({products,onProductsChange,storageKey,onNotice}:Props){
 const [suppliers,setSuppliers]=useState<Supplier[]>([]);const [purchases,setPurchases]=useState<Purchase[]>([]);const [selected,setSelected]=useState<Supplier|null>(null);const [query,setQuery]=useState('');const [showForm,setShowForm]=useState(false);const [editing,setEditing]=useState<Supplier|null>(null)
 const [name,setName]=useState('');const [contact,setContact]=useState('');const [phone,setPhone]=useState('');const [email,setEmail]=useState('');const [address,setAddress]=useState('');const [cuit,setCuit]=useState('');const [website,setWebsite]=useState('');const [notes,setNotes]=useState('')
 const [purchaseSupplier,setPurchaseSupplier]=useState('');const [purchaseDate,setPurchaseDate]=useState(new Date().toISOString().slice(0,10));const [payment,setPayment]=useState('Pendiente');const [reference,setReference]=useState('');const [discount,setDiscount]=useState('');const [purchaseItems,setPurchaseItems]=useState<{productId:number;name:string;quantity:number;unitPrice:number;total:number}[]>([]);const [productId,setProductId]=useState('');const [qty,setQty]=useState('1');const [unitCost,setUnitCost]=useState('')
 useEffect(()=>{setSuppliers(read(`${storageKey}-suppliers`,[]));setPurchases(read(`${storageKey}-purchases`,[]))},[storageKey]);useEffect(()=>{try{localStorage.setItem(`${storageKey}-suppliers`,JSON.stringify(suppliers));localStorage.setItem(`${storageKey}-purchases`,JSON.stringify(purchases))}catch{}},[storageKey,suppliers,purchases])
 const filtered=useMemo(()=>suppliers.filter(s=>`${s.name} ${s.contact} ${s.phone} ${s.email} ${s.cuit}`.toLowerCase().includes(query.toLowerCase())),[suppliers,query]);const supplierProducts=(s:Supplier)=>products.filter(p=>s.productIds.includes(p.id));const supplierPurchases=(s:Supplier)=>purchases.filter(p=>p.supplierId===s.id);const debt=(s:Supplier)=>supplierPurchases(s).filter(p=>p.payment!=='Pagado').reduce((a,p)=>a+p.total,0);const subtotal=purchaseItems.reduce((a,i)=>a+i.total,0);const disc=Math.max(0,Number(discount)||0);const total=Math.max(0,subtotal-disc)
 const resetForm=()=>{setName('');setContact('');setPhone('');setEmail('');setAddress('');setCuit('');setWebsite('');setNotes('');setEditing(null);setShowForm(false)}
 const saveSupplier=(e:FormEvent)=>{e.preventDefault();if(!name.trim()){onNotice('⚠️ Ingresá el nombre del proveedor.');return}const current=editing||{id:Date.now(),productIds:[]};const next={...current,name:name.trim(),contact:contact.trim(),phone:phone.trim(),email:email.trim(),address:address.trim(),cuit:cuit.trim(),website:website.trim(),notes:notes.trim()};setSuppliers(v=>editing?v.map(s=>s.id===editing.id?next:s):[next,...v]);setSelected(next);resetForm();onNotice(editing?'✅ Proveedor actualizado.':'✅ Proveedor agregado.')}
 const editSupplier=(s:Supplier)=>{setEditing(s);setName(s.name);setContact(s.contact);setPhone(s.phone);setEmail(s.email);setAddress(s.address);setCuit(s.cuit);setWebsite(s.website);setNotes(s.notes);setShowForm(true)}
 const removeSupplier=(s:Supplier)=>{if(!window.confirm(`¿Eliminar a ${s.name}?`))return;setSuppliers(v=>v.filter(x=>x.id!==s.id));if(selected?.id===s.id)setSelected(null);onNotice('Proveedor eliminado.')}
 const linkProduct=(s:Supplier,pid:number)=>{setSuppliers(v=>v.map(x=>x.id===s.id?{...x,productIds:Array.from(new Set([...x.productIds,pid]))}:x));onNotice('Producto vinculado al proveedor.')}
 const unlinkProduct=(s:Supplier,pid:number)=>setSuppliers(v=>v.map(x=>x.id===s.id?{...x,productIds:x.productIds.filter(id=>id!==pid)}:x))
 const addPurchaseItem=()=>{const p=products.find(x=>x.id===Number(productId));const q=Math.max(1,Number(qty)||1);const c=Math.max(0,Number(unitCost)||0);if(!p||!c){onNotice('Seleccioná producto y costo de compra.');return}const exists=purchaseItems.find(i=>i.productId===p.id);setPurchaseItems(exists?purchaseItems.map(i=>i.productId===p.id?{...i,quantity:i.quantity+q,total:(i.quantity+q)*i.unitPrice}:i):[...purchaseItems,{productId:p.id,name:p.name,quantity:q,unitPrice:c,total:q*c}]);setProductId('');setQty('1');setUnitCost('')}
 const registerPurchase=(e:FormEvent)=>{e.preventDefault();const s=suppliers.find(x=>x.id===Number(purchaseSupplier));if(!s||!purchaseItems.length){onNotice('Seleccioná proveedor y agregá al menos un producto.');return}if(!purchaseDate){onNotice('Ingresá la fecha de compra.');return}const itemProducts=products.map(p=>{const item=purchaseItems.find(i=>i.productId===p.id);if(!item)return p;return {...p,cost:item.unitPrice,supplier:s.name}});onProductsChange(itemProducts);const purchase:Purchase={id:Date.now(),supplierId:s.id,supplierName:s.name,date:purchaseDate,payment,reference:reference.trim(),discount:disc,total,items:purchaseItems};setPurchases(v=>[purchase,...v]);setSuppliers(v=>v.map(x=>x.id===s.id?{...x,productIds:Array.from(new Set([...x.productIds,...purchaseItems.map(i=>i.productId)]))}:x));setPurchaseItems([]);setPurchaseSupplier('');setReference('');setDiscount('');onNotice(`✅ Compra registrada a ${s.name}. Costos de los productos actualizados.`)}
 return <section className='large-section'><div className='panel-heading'><div><span className='eyebrow'>COMPRAS Y ABASTECIMIENTO</span><h2>Proveedores</h2><small>Administrá proveedores, compras, costos y saldos pendientes.</small></div><button className='primary-btn' type='button' onClick={()=>{resetForm();setShowForm(true)}}>＋ Nuevo proveedor</button></div>
 <div className='toolbar'><input value={query} onChange={e=>setQuery(e.target.value)} placeholder='🔎 Buscar proveedor...'/></div>
 <div className='two-col'><div className='panel'><div className='client-list'>{filtered.map(s=><div className='client-row' key={s.id} onClick={()=>setSelected(s)} style={{cursor:'pointer'}}><span className='client-avatar'>🏢</span><div style={{flex:1}}><strong>{s.name}</strong><small>{s.contact||'Sin contacto'}{s.phone?` · ${s.phone}`:''}</small><small>{s.email||'Sin email'}{s.cuit?` · CUIT ${s.cuit}`:''}</small><small>{supplierProducts(s).length} productos · {supplierPurchases(s).length} compras · Deuda {money(debt(s))}</small></div><div style={{display:'flex',gap:6}}><button type='button' className='secondary-btn' onClick={e=>{e.stopPropagation();editSupplier(s)}}>Editar</button><button type='button' className='secondary-btn' onClick={e=>{e.stopPropagation();removeSupplier(s)}}>Eliminar</button></div></div>)}{!filtered.length&&<div className='empty-state'>Todavía no hay proveedores.</div>}</div></div>
 <form className='panel form-panel' onSubmit={saveSupplier}><h3>{editing?'Editar proveedor':'Nuevo proveedor'}</h3><label>Empresa / proveedor *</label><input value={name} onChange={e=>setName(e.target.value)} required/><label>Persona de contacto</label><input value={contact} onChange={e=>setContact(e.target.value)}/><label>WhatsApp / teléfono</label><input value={phone} onChange={e=>setPhone(e.target.value)}/><label>Email</label><input type='email' value={email} onChange={e=>setEmail(e.target.value)}/><label>Dirección</label><input value={address} onChange={e=>setAddress(e.target.value)}/><label>CUIT</label><input value={cuit} onChange={e=>setCuit(e.target.value)}/><label>Web / Instagram</label><input value={website} onChange={e=>setWebsite(e.target.value)}/><label>Notas</label><textarea rows={3} value={notes} onChange={e=>setNotes(e.target.value)}/><button className='primary-btn'>{editing?'Guardar cambios':'Agregar proveedor'}</button></form></div>
 <form className='panel form-panel' style={{marginTop:18}} onSubmit={registerPurchase}><div className='panel-heading'><div><h3>🛒 Registrar compra</h3><small>Al registrar una compra se actualiza el costo de los productos incluidos.</small></div></div><div className='two-col'><div><label>Proveedor *</label><select value={purchaseSupplier} onChange={e=>setPurchaseSupplier(e.target.value)} required><option value=''>Seleccionar...</option>{suppliers.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></div><div><label>Fecha *</label><input type='date' value={purchaseDate} onChange={e=>setPurchaseDate(e.target.value)} required/></div></div><label>Producto</label><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><select value={productId} onChange={e=>setProductId(e.target.value)} style={{flex:1,minWidth:220}}><option value=''>Seleccionar producto...</option>{products.filter(p=>p.active!==false).map(p=><option key={p.id} value={p.id}>{p.name} · costo actual {money(p.cost||0)}</option>)}</select><input type='number' min='1' value={qty} onChange={e=>setQty(e.target.value)} style={{width:90}}/><input type='number' min='0.01' step='0.01' value={unitCost} onChange={e=>setUnitCost(e.target.value)} placeholder='Costo unit.' style={{width:130}}/><button type='button' className='secondary-btn' onClick={addPurchaseItem}>Agregar</button></div>{purchaseItems.length>0&&<div className='table'>{purchaseItems.map(i=><div className='trow' key={i.productId}><span><b>{i.name}</b><small>{i.quantity} × {money(i.unitPrice)}</small></span><b>{money(i.total)}</b><button type='button' className='secondary-btn' onClick={()=>setPurchaseItems(v=>v.filter(x=>x.productId!==i.productId))}>Quitar</button></div>)}</div>}<div className='two-col'><div><label>Descuento</label><input type='number' min='0' step='1' value={discount} onChange={e=>setDiscount(e.target.value)} placeholder='0'/></div><div><label>Medio de pago</label><select value={payment} onChange={e=>setPayment(e.target.value)}><option>Pendiente</option><option>Pagado</option><option>Efectivo</option><option>Transferencia</option><option>Mercado Pago</option><option>Tarjeta</option></select></div></div><label>N.º de comprobante / referencia</label><input value={reference} onChange={e=>setReference(e.target.value)} placeholder='Opcional'/><div className='panel-heading'><div><small>Subtotal: {money(subtotal)} · Descuento: {money(disc)}</small><strong>Total: {money(total)}</strong></div><button className='primary-btn'>Registrar compra</button></div></form>
 {selected&&<section className='panel' style={{marginTop:18}}><div className='panel-heading'><div><h3>{selected.name}</h3><small>{selected.address||'Sin dirección'}{selected.email?` · ${selected.email}`:''}</small></div><div style={{display:'flex',gap:8}}><button className='secondary-btn' onClick={()=>editSupplier(selected)}>Editar</button><button className='secondary-btn' onClick={()=>setSelected(null)}>Cerrar</button></div></div><div className='report-grid'><div className='report-card'><small>Productos vinculados</small><strong>{supplierProducts(selected).length}</strong></div><div className='report-card'><small>Compras</small><strong>{supplierPurchases(selected).length}</strong></div><div className='report-card'><small>Saldo pendiente</small><strong>{money(debt(selected))}</strong></div><div className='report-card'><small>CUIT</small><strong>{selected.cuit||'—'}</strong></div></div><h4>Productos del proveedor</h4><div className='table'>{supplierProducts(selected).map(p=><div className='trow' key={p.id}><span><b>{p.name}</b><small>{p.sku} · Costo {money(p.cost||0)} · Stock {p.stock}</small></span><button className='secondary-btn' onClick={()=>unlinkProduct(selected,p.id)}>Quitar</button></div>)}<div style={{paddingTop:10}}><select defaultValue='' onChange={e=>e.target.value&&linkProduct(selected,Number(e.target.value))}><option value=''>＋ Vincular producto...</option>{products.filter(p=>!selected.productIds.includes(p.id)).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></div></div><h4>Historial de compras</h4>{supplierPurchases(selected).map(p=><div className='trow' key={p.id}><span><b>{new Date(p.date+'T12:00:00').toLocaleDateString('es-AR')}</b><small>{p.items.map(i=>`${i.name} x${i.quantity}`).join(' · ')}{p.reference?` · Ref. ${p.reference}`:''}</small></span><span>{p.payment}</span><b>{money(p.total)}</b></div>)}{!supplierPurchases(selected).length&&<div className='empty-state'>Todavía no hay compras registradas.</div>}</section>}
 </section>
}
